<?php
$js1 = array(
    array("library/jquery/jquery-1.10.2.min.js", false),
    array("library/inputmask/jquery.maskedinput-1.3.1.min.js", false),
    array("library/validate/jquery.validate-1.11.1.js", false),
    array("js/util.js", false),
    array("js/index.js", false)
);


$js2 = array(
    array("library/plastique/javascripts/application.js", false)
);

use br\com\cf\library\core\cache\Cache;
?>

<!DOCTYPE html>
<html>

    <head>
        <title><?php print(CF_APP_NAME); ?></title>
        <meta charset="utf-8">
        <!-- Always force latest IE rendering engine or request Chrome Frame -->
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <link href="library/plastique/stylesheets/application.css" media="screen" rel="stylesheet" type="text/css" />

        <!--[if lt IE 9]>
        <script src="library/plastique/javascripts/html5shiv.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/excanvas.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/iefix.js" type="text/javascript"></script>
        <link href="library/plastique/stylesheets/iefix.css" media="screen" rel="stylesheet" type="text/css" />
        <![endif]-->

        <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?php Cache::factory()->js($js1)->output()->clean(); ?>          

    </head>
    <body>

        <div id="modal" class="black-box modal hide fade">
            <div class="modal-header tab-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <span>Some modal title</span>
            </div>
            <div class="modal-body separator">
                <h4>Text in a modal</h4>
                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem.</p>
            </div>
            <div class="modal-footer">
                <div class="inner-well">
                    <a class="button mini rounded light-gray" data-dismiss="modal">Close</a>
                    <a class="button mini rounded blue">Save changes</a>
                </div>
            </div>
        </div>

        <div id="modal-gallery" class="black-box modal modal-gallery hide fade">
            <div class="modal-header tab-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <span class="modal-title"></span>
            </div>
            <div class="modal-body"><div class="modal-image"></div></div>
            <div class="modal-footer">
                <div class="pull-left">
                    You can also change the images<br/> by scrolling the mouse wheel!
                </div>
                <div class="pull-right">
                    <a class="button blue modal-next">Next <i class="icon-arrow-right icon-white"></i></a>
                    <a class="button gray modal-prev"><i class="icon-arrow-left icon-white"></i> Previous</a>
                    <a class="button green modal-play modal-slideshow" data-slideshow="5000"><i class="icon-play icon-white"></i> Slideshow</a>
                    <a class="button black" target="_blank"><i class="icon-download"></i> Download</a>
                </div>
            </div>
        </div>

        <nav id="primary" class="main-nav">
            <ul>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Usuários <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/usuario/formCreate" href="#">
                                <i class="icon-search"></i> Novo
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Listar Todos
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Campeonatos <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Nova Master Liga
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Listar Campeonatos
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Nova Copa - Grupos
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Nova Copa - Finais
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Encerrar Copa
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Jogos <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Cancelar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Listar Todos 
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Editar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Liberar Rodadas
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Master Liga <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Configurações
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Nova Notícia
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Gerenciar Empréstimos 
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Gerenciar Leilões
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Premiar Jogadores
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Multar Jogadores
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Transferir Dinheiro
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Gerenciar Salários
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Gerenciar Patrocínios
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Configurar Email
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Jogadores <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Listar Todos
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-group"></i>Clubes <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/clube/search" href="#">
                                <i class="icon-warning-sign"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/clube/list" href="#">
                                <i class="icon-off"></i> Listar Todos
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class=" icon-trophy"></i>Seleções <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/selecao/search" href="#">
                                <i class="icon-warning-sign"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/selecao/list" href="#">
                                <i class="icon-off"></i> Listar Todas
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class=" icon-trophy"></i>Notificações <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/selecao/search" href="#">
                                <i class="icon-warning-sign"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/selecao/list" href="#">
                                <i class="icon-off"></i> Listar Todas
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class=" icon-trophy"></i>Configurações <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/selecao/search" href="#">
                                <i class="icon-warning-sign"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/selecao/list" href="#">
                                <i class="icon-off"></i> Listar Todas
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="">
                    <a href="/usuario/logoff">
                        <i class="icon-off"></i> Sair
                    </a>
                </li>

            </ul>
        </nav>

        <nav id="secondary" class="main-nav">

            <div class="profile-menu">

                <div class="pull-left">
                    <div class="avatar">
                        <img src="/img/avatars/admin.png" />
                    </div>
                </div>

                <div class="pull-left">
                    <div class="title">
                        <?php print($this->nm_usuario); ?>
                    </div>
                    <div class="btn-group">
                        <button class="button mini inset black"><i class="icon-search"></i></button>
                        <button class="button mini inset black">Online</button>
                        <button class="button mini inset black dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i></button>
                        <ul class="dropdown-menu black-box-dropdown">
                            <li><a href="#">Perfil</a></li>
                            <li><a href="#">Amigos</a></li>
                            <li><a href="#">Notificações</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Configurações</a></li>
                        </ul>

                    </div>
                </div>

                <div class="pull-right profile-menu-nav-collapse">
                    <button class="button black"><i class="icon-reorder"></i></button>
                </div>

            </div>

            <ul class="secondary-nav-menu">
                <li class="">
                    <a href="stats.html">
                        <i class="icon-dashboard"></i> Selecionado
                    </a>
                </li>

                <li>
                    <a href="#" id="modal-link">
                        <i class="icon-random"></i> Informações
                    </a>
                </li>

                <li id="notification-full-image">
                    <a href="#">
                        <i class="icon-list-alt"></i> Saldo
                    </a>
                </li>

                <li id="notification-small-image">
                    <a href="#">
                        <i class="icon-table"></i> Chat
                    </a>
                </li>

                <li id="notification-small-image">
                    <a href="#">
                        <i class="icon-table"></i> Meus Replays
                    </a>
                </li>

                <li id="notification-small-image">
                    <a href="#">
                        <i class="icon-table"></i> Meus Rivais
                    </a>
                </li>

                <li id="notification-small-image">
                    <a href="#">
                        <i class="icon-table"></i> Agenda
                    </a>
                </li>

                <li id="notification-small-image">
                    <a href="#">
                        <i class="icon-table"></i> Youtube
                    </a>
                </li>
            </ul>

        </nav>

        <section  id="main" class="containercontent"></section>

        <script type="text/html" id="template-notification">
            <div class="notification animated fadeInLeftMiddle fast{{ item.itemClass }}">
            <div class="left">
            <div style="background-image: url({{ item.imagePath }})" class="{{ item.imageClass }}"></div>
            </div>
            <div class="right">
            <div class="inner">{{ item.text }}</div>
            <div class="time">{{ item.time }}</div>
            </div>

            <i class="icon-remove-sign hide"></i>
            </div>
        </script>
        <script type="text/html" id="template-notifications">
            <div class="container">
            <div class="row" id="notifications-wrapper">
            <div id="notifications" class="{{ bootstrapPositionClass }} notifications animated">
            <div id="dismiss-all" class="dismiss-all button blue">Dismiss all</div>
            <div id="content">
            <div id="notes"></div>
            </div>
            </div>
            </div>
            </div>
        </script>
        <script src="library/plastique/javascripts/application.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/docs.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/docs_charts.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/documentation.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/prettify.js" type="text/javascript"></script>

        <link href="library/plastique/stylesheets/prettify.css" media="screen" rel="stylesheet" type="text/css" />

        <script type="text/javascript">
            prettyPrint();
        </script>

    </body>

</html>