<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Hello World (CF)</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Le styles -->
        <link href="/library/twitterboopstrap/css/bootstrap.css" rel="stylesheet">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
                background-image: url('/img/wallpaper.jpg');
            }
            .hero-unit{
                background-color: #fff;
            }
            .btn16{
                width: 16px;
                height: 16px;
                cursor: pointer;
            }
            #message-box{
                z-index: 999999;
            }
            #modal-edit{
                z-index: 888888;
            }
            #message-box,#modal-edit{
                display: none;
            }
        </style>
        <link type="text/css" href="/library/jqueryui/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet" />
        <link href="/library/twitterboopstrap/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/library/tablesort/css/style.css" rel="stylesheet">


        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript" src="/library/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="/library/twitterboopstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/library/inputmask/jquery.maskedinput-1.3.min.js"></script>
        <script type="text/javascript" src="/library/validate/jquery.validate.pt-Br.js"></script>
        <script type="text/javascript" src="/library/validate/jquery.validate.cnpj.pt-Br.js"></script>
        <script type="text/javascript" src="/library/tablesort/js/jquery.tablesorter.min.js"></script>
        <script type="text/javascript" src="/library/jqueryui/js/jquery-ui-1.8.21.custom.min.js"></script>
        <script type="text/javascript" src="/js/util.js"></script>
        <script type="text/javascript" src="/js/index.js"></script>
        <script type="text/javascript" src="/js/produto.js"></script>
        <script type="text/javascript" src="/js/usuario.js"></script>
        <script type="text/javascript" src="/js/venda.js"></script>
        <script type="text/javascript" src="/js/promocao.js"></script>


    </head>

    <body>

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <div class="nav-header">
                        <ul class="nav">
                            <li class="active"><a href="#"><?php print("Olá, {$this->nm_usuario}"); ?></a></li>
                            <li><a href="/usuario/logoff">Sair</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <h1>Hello World (CF)!</h1>
                <p>Cerberos Framework (v1.0)</p>

                <hr>
                <hr>

                <!-- Example row of columns -->
                <div class="row">
                    <div class="containercontent">
                        <h3>Seja bem vindo(a)</h3>
                        <p><?php print("Olá, {$this->nm_usuario}"); ?>, em breve você poderá efetuar suas comprar aqui!</p>
                        <h2>Obrigado!</h2>
                    </div>
                </div>
            </div>

            <!--modaledit-->
            <div class="modal" id="modal-edit">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">×</a>
                    <h3 class="title"></h3>
                </div>
                <div class="modal-body">
                    <p class="content"></p>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary close-message-box">Ok</a>
                </div>
            </div>

            <!--messagebox-->
            <div class="modal" id="message-box">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">×</a>
                    <h3 class="title"></h3>
                </div>
                <div class="modal-body">
                    <p class="content"></p>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary close-message-box">Ok</a>
                </div>
            </div>

            <footer>
                <p>&copy; Hello World (CF) 2012</p>
            </footer>

        </div> <!-- /container -->
    </body>
</html>