<script type="text/javascript" src="library/datatables/plugins/jquery.dataTables.columnFilter.js"></script>

<style type="text/css">
    .dataTables_filter{
        display: none;
    }
    .avatar{
        width: 50px;
        height: 50px;
    }
</style>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Jogadores</a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i title="Pesquisa Avançada" id="bthSearchJogadorAdmin" class="icon-search"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div id="rowSearchJogadorAdmin" class="row-fluid hidden">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Pesquisa Avançada
                        <span class="pull-left">
                            <span class="options">
                                <a href="#"><i class="icon-search"></i></a>
                            </span>
                        </span>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="padded">
                                <?php foreach ($this->columns as $key => $attr): ?>
                                    <div class="input">
                                        <span id="filterListJogadorAdmin-<?php print current($attr); ?>"></span>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    Jogadores
                    <span class="pull-left">
                        <span class="options">
                            <a href="#"><i class="icon-user"></i></a>
                        </span>
                    </span>
                </div>
                <div  class="dataTables_wrapper" role="grid">
                    <table id="gridJogadorAdmin" class="table table-striped data-table dataTable">
                        <thead>
                            <?php foreach ($this->columns as $key => $attr): ?>
                            <th>
                            <div><?php print current($attr); ?></div>
                            </th>
                        <?php endforeach; ?>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">

    $(document).ready(function() {

        $("#btnDetailJogadorAdmin").die('click').live('click', function() {
            Util.showModal('Informações Jogador', 'Editar', '/jogador/formEdit/id_jogador/' + $(this).attr('id_jogador'));
        });

        $('#bthSearchJogadorAdmin').click(function() {
            Index.admin.btnSearchJogadorAdminHiddenToggle = !Index.admin.btnSearchJogadorAdminHiddenToggle;
            if (Index.admin.btnSearchJogadorAdminHiddenToggle) {
                $('#rowSearchJogadorAdmin').addClass('hidden');
            } else {
                $('#rowSearchJogadorAdmin').removeClass('hidden');
            }
        });
    });

    Index.admin.gridJogadorAdmin = $('#gridJogadorAdmin').dataTable({
        "bFilter": true,
        "bProcessing": true,
        "bServerSide": true,
        "sPaginationType": "full_numbers",
        "bJQueryUI": true,
        "sAjaxSource": "/jogador/loadGridSearch/ajax/true/",
        "oLanguage": {
            "sLengthMenu": "mostrar _MENU_",
            "sZeroRecords": "nenhum jogador encontrado",
            "sInfo": "mostrando _START_ até _END_ de _TOTAL_ jogadores",
            "sInfoEmpty": "mostrando 0 até 0 de 0 jogadores",
            "sInfoFiltered": "(filtrado de _MAX_ jogadores)"
        },
        "fnRowCallback": function(nRow, aData, iDisplayIndex) {
            $('td:eq(0)', nRow).html('<img id="btnDetailJogadorAdmin" id_jogador="' + aData[0] + '" class="avatar" src="/img/jogadores/fotos/' + aData[0] + '.png">');
            $('td:eq(3)', nRow).html(aData[3] + ' cm');
            $('td:eq(4)', nRow).html(aData[4] + ' kg');
            $('td:eq(8)', nRow).html('<img class="avatar" src="/img/clubes/logos/' + aData[8] + '.png">');
            $('td:eq(9)', nRow).html('<img class="avatar" src="/img/selecoes/logos/' + aData[9] + '.png">');
        }
    }).columnFilter({
        sPlaceHolder: "head:before",
        aoColumns: [
<?php foreach ($this->columns as $key => $attr): ?>
                {sSelector: "#filterListJogadorAdmin-<?php print current($attr); ?>"},
<?php endforeach; ?>
        ]}
    );

</script>