<?php
$css1 = array(
    array('library/jquery-ui-1.10.3.custom/css/ui-darkness/jquery-ui-1.10.3.custom.min.css', true),
    array('css/datatable.css', true)
);

$js1 = array(
    array("library/jquery/jquery-1.10.2.min.js", false),
    array("js/util.js", false),
    array("js/index.js", false),
    array("js/index.admin.global.js", false),
    array("js/index.admin.js", false)
);


$js2 = array(
    array("library/plastique/javascripts/application.js", false)
);

$js3 = array(
    array("library/plastique/javascripts/application.js", false)
);

use br\com\cf\library\core\cache\Cache;
?>

<!DOCTYPE html>
<html>

    <head>
        <title><?php print(CF_APP_NAME); ?></title>
        <meta charset="utf-8">
        <!-- Always force latest IE rendering engine or request Chrome Frame -->
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <link href="library/plastique/stylesheets/application.css" media="screen" rel="stylesheet" type="text/css" />

        <!--[if lt IE 9]>
        <script src="library/plastique/javascripts/html5shiv.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/excanvas.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/iefix.js" type="text/javascript"></script>
        <link href="library/plastique/stylesheets/iefix.css" media="screen" rel="stylesheet" type="text/css" />
        <![endif]-->

        <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?php Cache::factory()->js($js1)->output()->clean(); ?>          

    </head>
    <body>

        <?php print br\com\cf\library\core\view\View::partials('modal'); ?>

        <nav id="primary" class="main-nav">
            <ul>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-trophy"></i>Master Liga <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <!--quando iniciada soh pode ter uma aberta, esta vinculada a tabela temporada-->
                        <?php if (!$this->temporada): ?>
                            <li>
                                <a class="linkcontent" value="/masterLiga/formCreate" href="#">
                                    <i class="icon-search"></i> Nova
                                </a>
                            </li>
                            <!--quando iniciada soh pode ter uma aberta, esta vinculada a tabela temporada-->
                            <li class="divider"></li>
                        <?php else: ?>
                            <!--quando iniciada soh pode ter uma aberta, esta vinculada a tabela temporada-->
                            <li>
                                <a class="linkcontent" value="/masterLiga/formClose" href="#">
                                    <i class="icon-search"></i> Encerrar
                                </a>
                            </li>
                            <!--quando iniciada soh pode ter uma aberta, esta vinculada a tabela temporada-->
                            <li class="divider"></li>
                        <?php endif; ?>
                        <li>
                            <a class="linkcontent" value="/masterLiga/formGames" href="#">
                                <i class="icon-search"></i> Jogos
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/masterLiga/formSale" href="#">
                                <i class="icon-list"></i> Leilões
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/masterLiga/formReward" href="#">
                                <i class="icon-list"></i> Premiar (Usuários)
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/masterLiga/formPunish" href="#">
                                <i class="icon-list"></i> Multar (Usuários)
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/masterLiga/formConfiguration" href="#">
                                <i class="icon-circle-arrow-down"></i> Configurações
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Copas <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/copa/formCreate" href="#">
                                <i class="icon-list"></i> Nova
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/copa/list" href="#">
                                <i class="icon-search"></i> Listar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/copa/gamesAdmin" href="#">
                                <i class="icon-search"></i> Jogos
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Jogadores <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Editar
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Usuários <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/usuario/formCreate" href="#">
                                <i class="icon-search"></i> Novo
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/usuario/list" href="#">
                                <i class="icon-list"></i> Listar
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-trophy"></i>Notificações <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/selecao/search" href="#">
                                <i class="icon-warning-sign"></i> Pesquisar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/selecao/list" href="#">
                                <i class="icon-off"></i> Listar Todas
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class=" icon-trophy"></i>Configuração <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/clube/list" href="#">
                                <i class="icon-warning-sign"></i> Clubes
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/selecao/list" href="#">
                                <i class="icon-off"></i> Seleções
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/selecao/list" href="#">
                                <i class="icon-off"></i> Seleções
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="">
                    <a href="/usuario/logoff">
                        <i class="icon-off"></i> Sair
                    </a>
                </li>

            </ul>
        </nav>

        <nav id="secondary" class="main-nav">

            <div class="profile-menu">

                <div class="pull-left">
                    <div class="avatar">
                        <img src="https://avatar-ssl.xboxlive.com/avatar/<?php print($this->usuario->lg_live); ?>/avatarpic-l.png" />
                    </div>
                </div>

                <div class="pull-left">
                    <div class="title">
                        <?php print($this->usuario->nm_usuario); ?>
                    </div>
                    <div class="btn-group">
                        <button class="button mini inset black"><i class="icon-search"></i></button>
                        <button class="button mini inset black"><?php print($this->usuario->nm_equipe); ?></button>
                        <button class="button mini inset black dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i></button>
                        <ul class="dropdown-menu black-box-dropdown">
                            <li><a href="#">Perfil</a></li>
                            <li><a href="#">Amigos</a></li>
                            <li><a href="#">Notificações</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Configurações</a></li>
                        </ul>

                    </div>
                </div>

                <div class="pull-right profile-menu-nav-collapse">
                    <button class="button black"><i class="icon-reorder"></i></button>
                </div>

            </div>

        </nav>

        <section  id="main" class="containercontent"></section>

        <script type="text/html" id="template-notification">
            <div class="notification animated fadeInLeftMiddle fast{{ item.itemClass }}">
            <div class="left">
            <div style="background-image: url({{ item.imagePath }})" class="{{ item.imageClass }}"></div>
            </div>
            <div class="right">
            <div class="inner">{{ item.text }}</div>
            <div class="time">{{ item.time }}</div>
            </div>

            <i class="icon-remove-sign hide"></i>
            </div>
        </script>
        <script type="text/html" id="template-notifications">
            <div class="container">
            <div class="row" id="notifications-wrapper">
            <div id="notifications" class="{{ bootstrapPositionClass }} notifications animated">
            <div id="dismiss-all" class="dismiss-all button blue">Fechar</div>
            <div id="content">
            <div id="notes"></div>
            </div>
            </div>
            </div>
            </div>
        </script>
        <script src="library/plastique/javascripts/application.js" type="text/javascript"></script>
        <!--<script src="library/plastique/javascripts/docs.js" type="text/javascript"></script>-->
        <!--<script src="library/plastique/javascripts/docs_charts.js" type="text/javascript"></script>-->
        <!--<script src="library/plastique/javascripts/documentation.js" type="text/javascript"></script>-->
        <!--<script src="library/plastique/javascripts/prettify.js" type="text/javascript"></script>-->

        <!--<link href="library/plastique/stylesheets/prettify.css" media="screen" rel="stylesheet" type="text/css" />-->

        <script type="text/javascript">
            //            prettyPrint();
        </script>

        <?php Cache::factory()->css($css1)->output()->clean(); ?>          

    </body>

</html>