<?php
$js1 = array(
    array("library/jquery/jquery-1.10.2.min.js", false),
    array("js/util.js", false),
    array("js/index.js", false),
    array("js/index.user.js", false),
    array("js/index.user.global.js", false)
);

$js2 = array(
    array("library/plastique/javascripts/application.js", false)
);

use br\com\cf\library\core\cache\Cache;
?>

<!DOCTYPE html>
<html>

    <head>
        <title><?php print(CF_APP_NAME); ?></title>
        <meta charset="utf-8">
        <!-- Always force latest IE rendering engine or request Chrome Frame -->
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <link href="library/plastique/stylesheets/application.css" media="screen" rel="stylesheet" type="text/css" />

        <!--[if lt IE 9]>
        <script src="library/plastique/javascripts/html5shiv.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/excanvas.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/iefix.js" type="text/javascript"></script>
        <link href="library/plastique/stylesheets/iefix.css" media="screen" rel="stylesheet" type="text/css" />
        <![endif]-->

        <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?php Cache::factory()->js($js1)->output()->clean(); ?>          

    </head>
    <body>

        <nav id="primary" class="main-nav">
            <ul>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Master Liga <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Trocar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Propostas Pendentes
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Transações da Liga
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Contratar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Gerenciar
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Salários
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Conta Corrente
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Leilões
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Equipe 
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Transações
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Campeonatos <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Calendário
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/search" href="#">
                                <i class="icon-search"></i> Classificação
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/jogador/list" href="#">
                                <i class="icon-list"></i> Jogos
                            </a>
                        </li>
                    </ul>
                </li>

                <li id="container" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>Copas <span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="linkcontent" value="/copa/groups" href="#">
                                <i class="icon-search"></i> Grupos
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/copa/finals" href="#">
                                <i class="icon-search"></i> Finais
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/copa/games" href="#">
                                <i class="icon-list"></i> Jogos
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="linkcontent" value="/copa/artillery" href="#">
                                <i class="icon-list"></i> Artilharia
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="">
                    <a href="/usuario/logoff">
                        <i class="icon-off"></i> Sair
                    </a>
                </li>

            </ul>
        </nav>

        <nav id="secondary" class="main-nav">

            <div class="profile-menu">

                <div class="pull-left">
                    <div class="avatar">
                        <img src="https://avatar-ssl.xboxlive.com/avatar/<?php print($this->usuario->lg_live); ?>/avatarpic-l.png" />
                    </div>
                </div>

                <div class="pull-left">
                    <div class="title">
                        <?php print(current(explode(' ', $this->usuario->nm_usuario))); ?>
                    </div>
                    <div class="btn-group">
                        <button class="button mini inset black"><i class="icon-search"></i></button>
                        <button class="button mini inset black"><?php print($this->usuario->nm_equipe); ?></button>
                        <button class="button mini inset black dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i></button>
                        <ul class="dropdown-menu black-box-dropdown">
                            <li><a href="#">Perfil</a></li>
                            <li><a href="#">Amigos</a></li>
                            <li><a href="#">Notificações</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Configurações</a></li>
                        </ul>

                    </div>
                </div>

                <div class="pull-right profile-menu-nav-collapse">
                    <button class="button black"><i class="icon-reorder"></i></button>
                </div>

            </div>

            <ul class="secondary-nav-menu">
                <li class="active">
                    <a href="#">
                        <i class=""></i> Banco
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-adjust"></i> Saldo: R$ 19.000,00
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-adjust"></i> Saldo: R$ 19.000,00
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="icon-money"></i> Salário: R$ 23.000,00
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="icon-magnet"></i> Total: R$ 23.000,00
                    </a>
                </li>

                <li>
                    <a href="#">
<!--                        <i class="icon-magnet"></i> Total: R$ 23.000,00-->
                    </a>
                </li>
                <li>
                    <a href="#">
<!--                        <i class="icon-magnet"></i> Total: R$ 23.000,00-->
                    </a>
                </li>

                <li id="">
                    <a href="#">
                        <i class="icon-list-alt"></i> Saldo
                    </a>
                </li>

                <li id="">
                    <a href="#">
                        <i class="icon-table"></i> Chat
                    </a>
                </li>

                <li id="">
                    <a href="#">
                        <i class="icon-table"></i> Meus Replays
                    </a>
                </li>

                <li id="">
                    <a href="#">
                        <i class="icon-table"></i> Meus Rivais
                    </a>
                </li>

                <li id="">
                    <a href="#">
                        <i class="icon-table"></i> Agenda
                    </a>
                </li>

                <li id="">
                    <a class="linkcontent" value="index/home" href="#">
                        <i class="icon-table"></i> Youtube
                    </a>
                </li>

                <li id="">
                    <a class="linkcontent" value="index/forum" href="#">
                        <i class="icon-table"></i> Fórum
                    </a>
                </li>

                <li>
                    <img class="img-rounded center"  src="img/escudos/36.png">
                </li>
            </ul>

        </nav>

        <section  id="main" class="containercontent"></section>

        <script type="text/html" id="template-notification">
            <div class="notification animated fadeInLeftMiddle fast{{ item.itemClass }}">
            <div class="left">
            <div style="background-image: url({{ item.imagePath }})" class="{{ item.imageClass }}"></div>
            </div>
            <div class="right">
            <div class="inner">{{ item.text }}</div>
            <div class="time">{{ item.time }}</div>
            </div>

            <i class="icon-remove-sign hide"></i>
            </div>
        </script>
        <script type="text/html" id="template-notifications">
            <div class="container">
            <div class="row" id="notifications-wrapper">
            <div id="notifications" class="{{ bootstrapPositionClass }} notifications animated">
            <div id="dismiss-all" class="dismiss-all button blue">Dismiss all</div>
            <div id="content">
            <div id="notes"></div>
            </div>
            </div>
            </div>
            </div>
        </script>
        <script src="library/plastique/javascripts/application.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/docs.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/docs_charts.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/documentation.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/prettify.js" type="text/javascript"></script>

        <link href="library/plastique/stylesheets/prettify.css" media="screen" rel="stylesheet" type="text/css" />

        <script type="text/javascript">
            prettyPrint();
        </script>

    </body>

</html>