<style type="text/css">
    .mini-img-in-grid{
        width: 50px;
        height: 50px;
        border: 0px;
    }

</style>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Listar Todos Clubes</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    Clubes
                </div>
                <table id="tabela" class="table table-striped table-condensed">
                    <thead>
                    <th>
                    <div>#</div>
                    </th>
                    <th>
                    <div>Nome</div>
                    </th>
                    <th>
                    <div>Pais</div>
                    </th>
                    </thead>
                </table>

            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#tabela').dataTable({
            "bFilter": true,
            "bProcessing": true,
            "bServerSide": true,
            "sPaginationType": "full_numbers",
            "bJQueryUI": false,
            "sAjaxSource": "/clube/loadGridSearch/ajax/true/",
            "oLanguage": {
                "oPaginate": {
                    "sFirst": "Primeira",
                    "sPrevious": "Anterior",
                    "sNext": "Próxima",
                    "sLast": "Última"
                },
                "sSearch": "Filtrar:",
                "sLengthMenu": "_MENU_",
                "sZeroRecords": "Nenhum clube encontrado",
                "sInfo": "Visualizando _START_ até _END_ de _TOTAL_ clubes",
                "sInfoEmpty": "Visualizando 0 até 0 de 0 clubes",
                "sInfoFiltered": "(filtrado de _MAX_ clubes)"
            },
            "fnRowCallback": function(nRow, aData, iDisplayIndex) {
                $('td:eq(0)', nRow).html('<img class="mini-img-in-grid" src="/img/clubes/logos/' + aData[0] + '.png">');
                $('td:eq(4)', nRow).html(aData[4] + '<b> cm</b>');
                $('td:eq(5)', nRow).html(aData[5] + '<b> kg</b>');
            }
        });
    });
</script>