<h2>Lista de Produtos</h2>
<hr>
<table class="table table-bordered table-striped tablesorter">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->produtos as $produto) : ?>
            <tr>
                <td><?php print($produto['nm_produto']); ?></td>
                <td><?php ($produto['vl_desconto']) ? print("(Em promoção) De R$ {$produto['vl_produto']} por R$ {$produto['vl_desconto']}")  : print("R$ {$produto['vl_produto']}"); ?></td>
                <td>
                    <img title="Editar" class="btn16" onClick="Produto.editarProduto(<?php print($produto['id_produto']); ?>)" src="/img/edit.png">
                    <img title="Excluir" class="btn16" onClick="Produto.excluirProduto(<?php print($produto['id_produto']); ?>)" src="/img/delete.png"> 
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
        !(function($){
        'use strict'
        $(document).ready(function(){
            $(".table").tablesorter();
        });
    })(jQuery);
</script>