<?php sleep(15); ?>

<div class="row">
    <div class="span10">
        <h3>Downloads Premium</h3>
    </div>
</div>

<hr>

<div class="row">
    <div class="alert alert-success span5">
        <p>Servidores Disponíveis</p>
        <span class="label label-success">jumbofiles</span>
        <span class="label label-success">uploaded</span>
        <span class="label label-success">rapidshare</span>
        <span class="label label-success">4shared</span>
        <span class="label label-success">uploadboost</span>
        <span class="label label-success">hotfile</span>
        <span class="label label-success">uploading</span>
        <span class="label label-success">crocko</span>
        <span class="label label-success">sendspace</span>
        <span class="label label-success">bitshare</span>  
    </div>

    <div class="alert alert-error span5">
        <p>Servidores Indisponíveis</p>
        <span class="label label-important">megaupload</span>
        <span class="label label-important">mediafire</span>
        <span class="label label-important">fileserve</span>
        <span class="label label-important">uploadstation</span>
        <span class="label label-important">filefactory</span>
        <span class="label label-important">videobb</span>
        <span class="label label-important">filesonic</span>
        <span class="label label-important">depositFiles</span>
        <span class="label label-important">ul.to</span>
        <span class="label label-important">easy-share</span>
        <span class="label label-important">wupload</span>
        <span class="label label-important">filejungle</span>

    </div>

</div>

<hr>

<div class="row">
    <div class="span10">
        <div class="control-group center">
            <div class="controls">
                <div class="input-append">
                    Link
                    <input id="url" class="input-xxlarge" type="text" name="url" value="https://rapidshare.com/#!download|698p8|215942844|WXP75MBEng.rar|69168|0|0">
                    <button id="btnDownloadPremium" class="btn btn-success" type="button">Gerar Download!</button>
                </div>
            </div>
        </div>
    </div>
</div>