<?php
$css1 = array(
    array("library/jquery-jsplumb/demo/demo-all.css", false),
    array("library/jquery-jsplumb/demo/chart/demo.css", false),
);

$js1 = array(
    array("library/jquery-jsplumb/lib/jquery-1.9.0.js", true),
    array("library/jquery-jsplumb/lib/jsplumb-geom-0.1.js", true),
    array("library/jquery-jsplumb/src/util.js", true),
    array("library/jquery-jsplumb/src/dom-adapter.js", true),
    array("library/jquery-jsplumb/src/jsPlumb.js", true),
    array("library/jquery-jsplumb/src/endpoint.js", true),
    array("library/jquery-jsplumb/src/connection.js", true),
    array("library/jquery-jsplumb/src/anchors.js", true),
    array("library/jquery-jsplumb/src/defaults.js", true),
    array("library/jquery-jsplumb/src/connectors-flowchart.js", true),
    array("library/jquery-jsplumb/src/renderers-svg.js", true),
    array("library/jquery-jsplumb/src/renderers-canvas.js", true),
    array("library/jquery-jsplumb/src/renderers-vml.js", true),
    array("library/jquery-jsplumb/src/jquery.jsPlumb.js", true),
    array("library/jquery-jsplumb/demo/chart/demo.js", true),
);


br\com\cf\library\core\cache\Cache::factory()->css($css1)->output()->clean();
?>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Copas </a></li>
                        <li><a href="#"><i class="icon-home"></i> Jogos </a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i title="Pesquisa Avançada" id="bthSearchJogadorAdmin" class="icon-search"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid"></div>
        <div class="span12">
            <div class="chart-demo" id="chart-demo">

                <!--SUPERIOR - INICIO-->

                <div class="window" id="chartWindow2-1-up">
                    <img class="avatar" src="img/selecoes/logos/1335.png">
                </div>

                <div class="window" id="chartWindow3-1-up">
                    <img class="avatar" src="img/selecoes/logos/1335.png">
                </div>
                <div class="window" id="chartWindow3-2-up">
                    <img class="avatar" src="img/selecoes/logos/1331.png">
                </div>

                <div class="window" id="chartWindow4-1-up">
                    <img class="avatar" src="img/selecoes/logos/1335.png">
                </div>
                <div class="window" id="chartWindow4-2-up">
                    <img class="avatar" src="img/selecoes/logos/1359.png">
                </div>
                <div class="window" id="chartWindow4-3-up">
                    <img class="avatar" src="img/selecoes/logos/1331.png">
                </div>
                <div class="window" id="chartWindow4-4-up">
                    <img class="avatar" src="img/selecoes/logos/1364.png">
                </div>

                <div class="window" id="chartWindow5-1-up">
                    <img class="avatar" src="img/selecoes/logos/1335.png">
                </div>
                <div class="window" id="chartWindow5-2-up">
                    <img class="avatar" src="img/selecoes/logos/1318.png">
                </div>
                <div class="window" id="chartWindow5-3-up">
                    <img class="avatar" src="img/selecoes/logos/1359.png">
                </div>
                <div class="window" id="chartWindow5-4-up">
                    <img class="avatar" src="img/selecoes/logos/1365.png">
                </div>
                <div class="window" id="chartWindow5-5-up">
                    <img class="avatar" src="img/selecoes/logos/1377.png">
                </div>
                <div class="window" id="chartWindow5-6-up">
                    <img class="avatar" src="img/selecoes/logos/1331.png">
                </div>
                <div class="window" id="chartWindow5-7-up">
                    <img class="avatar" src="img/selecoes/logos/1370.png">
                </div>
                <div class="window" id="chartWindow5-8-up">
                    <img class="avatar" src="img/selecoes/logos/1364.png">
                </div>

                <!--SUPERIOR - FIM-->

                <div class="window" id="chartWindow1-1">
                    <img class="avatar" src="img/clubes/logos/1.png">
                </div>

                <!--INFERIOR - INICIO-->

                <div class="window" id="chartWindow2-1">
                    <img class="avatar" src="img/clubes/logos/1.png">
                </div>

                <div class="window" id="chartWindow3-1">
                    <img class="avatar" src="img/clubes/logos/1.png">
                </div>
                <div class="window" id="chartWindow3-2">
                    <img class="avatar" src="img/clubes/logos/8.png">
                </div>

                <div class="window" id="chartWindow4-1">
                    <img class="avatar" src="img/clubes/logos/1.png">
                </div>
                <div class="window" id="chartWindow4-2">
                    <img class="avatar" src="img/clubes/logos/3.png">
                </div>
                <div class="window" id="chartWindow4-3">
                    <img class="avatar" src="img/clubes/logos/8.png">
                </div>
                <div class="window" id="chartWindow4-4">
                    <img class="avatar" src="img/clubes/logos/10.png">
                </div>

                <div class="window" id="chartWindow5-1">
                    <img class="avatar" src="img/clubes/logos/1.png">
                </div>
                <div class="window" id="chartWindow5-2">
                    <img class="avatar" src="img/clubes/logos/2.png">
                </div>
                <div class="window" id="chartWindow5-3">
                    <img class="avatar" src="img/clubes/logos/3.png">
                </div>
                <div class="window" id="chartWindow5-4">
                    <img class="avatar" src="img/clubes/logos/4.png">
                </div>
                <div class="window" id="chartWindow5-5">
                    <img class="avatar" src="img/clubes/logos/7.png">
                </div>
                <div class="window" id="chartWindow5-6">
                    <img class="avatar" src="img/clubes/logos/8.png">
                </div>
                <div class="window" id="chartWindow5-7">
                    <img class="avatar" src="img/clubes/logos/9.png">
                </div>
                <div class="window" id="chartWindow5-8">
                    <img class="avatar disabled" src="img/clubes/logos/10.png">
                </div>

                <!--INFERIOR - FIM-->

            </div>
        </div>
        <?php print br\com\cf\library\core\view\View::partials('footer'); ?>
    </div>
</section>

<?php br\com\cf\library\core\cache\Cache::factory()->js($js1)->output()->clean(); ?>