<style type="text/css">
    .logo-clube-150{
        width: 100px;
        height: 100px;
    }
</style>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Listar Todos Clubes</a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i class="icon-search"></i></a>
                </div>
            </div>

            <div class="row-fluid search-bar-nav">
                <div class="span12">
                    <form>
                        <input class="search" placeholder="Search..." type="text">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    Clubes
                </div>
                <div  class="dataTables_wrapper" role="grid">

                    <table id="tabela" class="table table-striped data-table dataTable">
                        <thead>
                            <tr role="row">
                                <th style="width: 150px;" colspan="1" rowspan="1" tabindex="0" class="ui-state-default">
                        <div class="DataTables_sort_wrapper">#<span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-n"></span></div>
                        </th>
                        <th style="width: 150px;" colspan="1" rowspan="1" tabindex="0" class="ui-state-default">
                        <div class="DataTables_sort_wrapper">Nome<span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-n"></span></div>
                        </th>
                        <th style="width: 226px;" colspan="1" rowspan="1" class="ui-state-default">
                        <div class="DataTables_sort_wrapper">Pais<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                        </th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function(){
    $('#tabela').dataTable({
    "bProcessing": true,
    "bServerSide": true,
    "sPaginationType": "full_numbers",
    "bJQueryUI": true,
    "sAjaxSource": "/clube/loadGridSearch/ajax/true/",
    "oLanguage": {
    "sLengthMenu": "mostrar _MENU_",
    "sZeroRecords": "nenhum clube encontrado",
    "sInfo": "mostrando _START_ até _END_ de _TOTAL_ clubes",
    "sInfoEmpty": "mostrando 0 até 0 de 0 clubes",
    "sInfoFiltered": "(filtrado de _MAX_ clubes)"
    },
    "fnRowCallback": function( nRow, aData, iDisplayIndex ) {
    $('td:eq(0)', nRow).html('<img class="logo-clube-150" src="/img/clubes/logos/'+aData[0]+'.png">');
    $('td:eq(4)', nRow).html( aData[4]+'<b> cm</b>' );
    $('td:eq(5)', nRow).html( aData[5]+'<b> kg</b>' );
    }
    });
    });
</script>