insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (54,'Brasil','Ámérica do Sul','BRA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (14,'Inglaterra','Europa','ENG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (27,'Itália','Europa','ITA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (18,'França','Europa','FRA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (45,'Espanha','Europa','ESP');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (21,'Alemanha','Europa','GER');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (7,'Bélgica','Europa','BEL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (38,'Portugal','Europa','POR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (52,'Argentina','Ámérica do Sul','ARG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (37,'Polônia','Europa','POL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (34,'Holanda','Europa','NED');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (83,'México','América do Norte','MEX');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (46,'Suécia','Europa','SWE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (50,'País de Gales','Europa','WAL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (167,'CORÉIA','Ásia','KOR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (25,'IRLANDA','Europa','IRL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (95,'Estados Unidos','América do Norte','USA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (48,'Turquia','Europa','TUR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (36,'Noruega','Europa','NOR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (42,'Escócia','Europa','SCO');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (13,'Dinamarca','Europa','DEN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (10,'Croácia','Europa','CRO');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (47,'Suíça','Europa','SUI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (56,'Colômbia','Ámérica do Sul','COL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (163,'Japão','Ásia','JPN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (195,'Austrália','Ásia','AUS');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (60,'Uruguai','Ámérica do Sul','URU');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (51,'Sérvia','Europa','SRB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (133,'Nigéria','África','NGA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (108,'COSTA DO MARFIM','África','CIV');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (12,'República Tcheca','Europa','CZE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (136,'Senegal','África','SEN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (4,'Áustria','Europa','AUT');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (40,'Rússia','Europa','RUS');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (22,'Grécia','Europa','GRE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (117,'Gana','África','GHA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (103,'Camarões','África','CMR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (129,'Marrocos','África','MAR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (8,'Bósnia-Herzegovina','Europa','BIH');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (15,'Montenegro','Europa','MNE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (39,'Romênia','Europa','ROU');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (43,'Eslováquia','Europa','SVK');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (140,'África do Sul','África','RSA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (3,'Armênia','Europa','ARM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (115,'Gabão','África','GAB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (49,'Ucrânia','Europa','UKR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (35,'Irlanda do Norte','Europa','NIR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (82,'Jamaica','América do Norte','JAM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (23,'Hungria','Europa','HUN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (70,'Canadá','América do Norte','CAN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (97,'Argélia','África','ALG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (183,'Arábia Saudita','Ásia','KSA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (55,'Chile','Ámérica do Sul','CHI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (61,'Venezuela','Ámérica do Sul','VEN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (110,'RD do CONGO','África','COD');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (58,'Paraguai','Ámérica do Sul','PAR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (126,'Mali','África','MLI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (155,'China','Ásia','CHN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (59,'Peru','Ámérica do Sul','PER');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (161,'Irã','Ásia','IRN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (57,'Equador','Ámérica do Sul','ECU');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (9,'Bulgária','Europa','BUL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (26,'Israel','Europa','ISR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (145,'Tunísia','África','TUN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (17,'Finlândia','Europa','FIN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (24,'Islândia','Europa','ISL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (44,'Eslovênia','Europa','SVN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (104,'CABO VERDE','África','CPV');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (19,'MACEDÔNIA','Europa','MKD');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (1,'Albânia','Europa','ALB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (107,'Congo','África','CGO');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (20,'Geórgia','Europa','GEO');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (198,'Nova Zelândia','Oceânia','NZL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (144,'Togo','África','TOG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (101,'Burkina Fasso','África','BFA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (118,'Guiné','África','GUI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (111,'Egito','África','EGY');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (81,'Honduras','América do Norte','HON');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (99,'Benin','África','BEN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (72,'Costa Rica','América do Norte','CRC');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (30,'Lituânia','Europa','LTU');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (93,'Trinidad e Tobago','América do Norte','TRI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (138,'Serra Leoa','África','SLE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (98,'Angola','África','ANG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (53,'Bolívia','Ámérica do Sul','BOL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (208,'Estônia','Europa','EST');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (148,'Zimbábue','África','ZIM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (181,'Filipinas','Ásia','PHI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (6,'Bielo-Rússia','Europa','BLR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (5,'Azerbaijão','Europa','AZE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (11,'Chipre','Europa','CYP');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (87,'Panamá','América do Norte','PAN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (80,'Haiti','América do Norte','HAI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (28,'Letônia','Europa','LVA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (166,'CORÉIA DO NORTE','Ásia','PRK');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (120,'Quênia','África','KEN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (162,'Iraque','Ásia','IRQ');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (165,'Casaquistão','Europa','KAZ');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (130,'Moçambique','África','MOZ');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (66,'Barbados','América do Norte','BRB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (171,'Líbano','Ásia','LIB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (178,'Omã','Ásia','OMA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (159,'Índia','Ásia','IND');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (116,'Gâmbia','África','GAM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (76,'El Salvador','América do Norte','SLV');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (122,'Libéria','África','LBR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (73,'Cuba','América do Norte','CUB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (147,'Zâmbia','África','ZAM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (78,'Guatemala','América do Norte','GUA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (119,'Guiné-Bissau','África','GNB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (131,'Namíbia','África','NAM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (202,'Taiti','Oceânia','TAH');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (105,'REP. CENTRO-AFRICANA','África','CTA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (16,'Ilhas Faroe','Europa','FRO');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (146,'Uganda','África','UGA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (31,'Luxemburgo','Europa','LUX');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (179,'Paquistão','Ásia','PAK');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (191,'Uzbequistão','Ásia','UZB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (128,'Maurício','África','MRI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (211,'Resto do Mundo','Outros','nation.code.211');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (68,'Bermuda','América do Norte','BER');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (186,'Síria','Ásia','SYR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (132,'Níger','África','NIG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (127,'Mauritânia','África','MTN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (102,'Burundi','África','BDI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (33,'Moldávia','Europa','MDA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (77,'Granada','América do Norte','GRN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (124,'Madagáscar','África','MAD');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (92,'Suriname','América do Norte','SUR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (29,'Liechtenstein','Europa','LIE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (134,'Ruanda','África','RWA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (85,'Antilhas Holandesas','América do Norte','ANT');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (88,'Porto Rico','América do Norte','PUR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (32,'Malta','Europa','MLT');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (182,'Catar','Ásia','QAT');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (62,'Anguila','América do Norte','AIA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (112,'Guiné Equatorial','África','EQG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (207,'República Dominicana','América do Norte','DOM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (89,'SÃO CRISTÓVÃO E NEVES','América do Norte','SKN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (135,'São Tomé e Príncipe','África','STP');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (139,'Somália','África','SOM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (125,'Malauí','África','MWI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (90,'SANTA LÚCIA','América do Norte','LCA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (150,'Bahrein','Ásia','BHR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (106,'Chade','África','CHA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (164,'Jordânia','Ásia','JOR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (114,'Etiópia','África','ETH');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (188,'Tailândia','Ásia','THA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (216,'Creation Centre','Outros','nation.code.216');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (210,'Niezrzeszony','Outros','nation.code.210');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (142,'Suazilândia','África','SWZ');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (160,'Indonésia','Ásia','IDN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (192,'Vietnã','Ásia','VIE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (41,'San Marino','Europa','SMR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (63,'Antígua e Barbuda','América do Norte','ATG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (121,'Lesoto','África','LES');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (94,'ILHAS TURKS E CAIOS','América do Norte','TCA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (84,'Montserrat','América do Norte','MSR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (149,'Afeganistão','Ásia','AFG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (2,'Andorra','Europa','AND');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (141,'Sudão','África','SUD');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (187,'Tadjiquistão','Ásia','TJK');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (65,'Bahamas','América do Norte','BAH');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (91,'SÃO VICENTE E GRANADINAS','América do Norte','VIN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (206,'Groenlândia','Outros','nation.code.206');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (209,'Jogadores Criados','Outros','nation.code.209');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (154,'Camboja','Ásia','CAM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (137,'Seychelles','África','SEY');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (215,'New Caledonia','Oceânia','NCL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (157,'Guam','Ásia','GUM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (67,'Belize','América do Norte','BLZ');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (214,'Timor Leste','África','COM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (205,'Gibraltar','Outros','nation.code.205');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (190,'Emirados Árabes Unidos','Ásia','UAE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (152,'Butão','Ásia','BHU');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (123,'Líbia','África','LBY');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (173,'Malásia','Ásia','MAS');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (185,'Sri Lanka','Ásia','SRI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (96,'ILHAS VIRGENS AMERICANAS','América do Norte','VIR');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (168,'Kuwait','Ásia','KUW');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (201,'Ilhas Salomão','Oceânia','SOL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (79,'Guiana','América do Norte','GUY');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (200,'Samoa','Oceânia','SAM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (199,'Papua-Nova Guiné','Oceânia','PNG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (153,'Brunei','Ásia','BRU');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (113,'Eritréia','África','ERI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (100,'Botsuana','África','BOT');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (176,'Mianmar','Ásia','MYA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (175,'Mongólia','Ásia','MGL');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (197,'Fiji','Oceânia','FIJ');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (203,'Tonga','Oceânia','TGA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (172,'Macau','Ásia','MAC');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (177,'Nepal','Ásia','NEP');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (213,'Nova Caledônia','Ásia','TPE');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (174,'Maldivas','Ásia','MDV');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (193,'Iêmen','Ásia','YEM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (194,'Samoa Americana','Oceânia','ASA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (212,'Comores','Ásia','TLS');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (69,'ILHAS VIRGENS BRITÂNICAS','América do Norte','VGB');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (75,'Internacional','Outros','nation.code.75');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (204,'Vanuatu','Oceânia','VAN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (143,'Tanzânia','África','TAN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (64,'Aruba','América do Norte','ARU');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (71,'Ilhas Cayman','América do Norte','CAY');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (170,'Laos','Ásia','LAO');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (196,'Ilhas Cook','Oceânia','COK');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (109,'Djibuti','África','DJI');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (169,'Quirguistão','Ásia','KGZ');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (151,'Bangladesh','Ásia','BAN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (158,'Hong Kong','Ásia','HKG');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (74,'Dominica','América do Norte','DMA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (86,'Nicarágua','América do Norte','NCA');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (189,'Turcomenistão','Ásia','TKM');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (184,'Cingapura','Ásia','SIN');
insert into pais (id_pais,nm_pais,nm_confederacao,cd_pais) values (180,'PALESTINA','Ásia','PLE');



select * from pais where id_pais = 209