insert into selecao (id_selecao,id_pais,nm_selecao) values (1370,54,"Brasil");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1343,27,"Itália");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1362,45,"Espanha");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1337,21,"Alemanha");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1335,18,"França");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1369,52,"Argentina");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1318,14,"Inglaterra");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1325,7,"Bélgica");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1377,60,"Uruguai");
insert into selecao (id_selecao,id_pais,nm_selecao) values (105035,34,"Holanda");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1354,38,"Portugal");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1386,83,"México");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1353,37,"Polônia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1387,95,"Estados Unidos");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1365,48,"Turquia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111109,56,"Colômbia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1363,46,"Suécia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (974,167,"Coréia do Sul");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1331,13,"Dinamarca");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1357,40,"Rússia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1395,103,"Camarões");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1364,47,"Suíça");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1415,195,"Austrália");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1338,22,"Grécia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111112,108,"Costa do Marfim");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1356,39,"Romênia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111465,57,"Equador");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1327,9,"Bulgária");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1886,23,"Hungria");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1322,4,"Áustria");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1352,36,"Noruega");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1355,25,"Irlanda");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1334,17,"Finlândia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1359,42,"Escócia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1361,44,"Eslovênia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1330,12,"República Tcheca");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111459,55,"Chile");
insert into selecao (id_selecao,id_pais,nm_selecao) values (1375,58,"Paraguai");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111473,198,"Nova Zelândia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111099,140,"África do Sul");
insert into selecao (id_selecao,id_pais,nm_selecao) values (110081,35,"Irlanda do Norte");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111108,59,"Peru");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111466,159,"Índia");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111130,111,"Egito");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111487,61,"Venezuela");
insert into selecao (id_selecao,id_pais,nm_selecao) values (111451,53,"Bolívia");
