insert into clube (sq_clube,sq_pais,nm_clube) values (241,45,"FC Barcelona");
insert into clube (sq_clube,sq_pais,nm_clube) values (243,45,"Real Madrid Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (5,14,"Chelsea");
insert into clube (sq_clube,sq_pais,nm_clube) values (11,14,"Manchester United");
insert into clube (sq_clube,sq_pais,nm_clube) values (47,27,"Milan");
insert into clube (sq_clube,sq_pais,nm_clube) values (22,21,"Borussia Dortmund");
insert into clube (sq_clube,sq_pais,nm_clube) values (1,14,"Arsenal");
insert into clube (sq_clube,sq_pais,nm_clube) values (21,21,"FC Bayern Munich");
insert into clube (sq_clube,sq_pais,nm_clube) values (45,27,"Juventus");
insert into clube (sq_clube,sq_pais,nm_clube) values (9,14,"Liverpool");
insert into clube (sq_clube,sq_pais,nm_clube) values (69,18,"AS Monaco FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (10,14,"Manchester City");
insert into clube (sq_clube,sq_pais,nm_clube) values (44,27,"Inter");
insert into clube (sq_clube,sq_pais,nm_clube) values (18,14,"Tottenham Hotspur");
insert into clube (sq_clube,sq_pais,nm_clube) values (73,18,"Paris Saint-Germain");
insert into clube (sq_clube,sq_pais,nm_clube) values (52,27,"Roma");
insert into clube (sq_clube,sq_pais,nm_clube) values (240,45,"Club Atlético de Madrid");
insert into clube (sq_clube,sq_pais,nm_clube) values (48,27,"Napoli");
insert into clube (sq_clube,sq_pais,nm_clube) values (237,38,"Sporting CP");
insert into clube (sq_clube,sq_pais,nm_clube) values (245,34,"Ajax");
insert into clube (sq_clube,sq_pais,nm_clube) values (66,18,"Olympique Lyonnais");
insert into clube (sq_clube,sq_pais,nm_clube) values (34,21,"FC Schalke 04");
insert into clube (sq_clube,sq_pais,nm_clube) values (236,38,"Porto");
insert into clube (sq_clube,sq_pais,nm_clube) values (110374,27,"ACF Fiorentina");
insert into clube (sq_clube,sq_pais,nm_clube) values (457,45,"Real Sociedad de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (461,45,"Valencia Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (1053,54,"Santos");
insert into clube (sq_clube,sq_pais,nm_clube) values (598,54,"São Paulo");
insert into clube (sq_clube,sq_pais,nm_clube) values (325,211,"Galatasaray SK");
insert into clube (sq_clube,sq_pais,nm_clube) values (573,45,"Málaga Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (111592,210,"Passes Livres");
insert into clube (sq_clube,sq_pais,nm_clube) values (13,14,"Newcastle United");
insert into clube (sq_clube,sq_pais,nm_clube) values (1041,54,"Corinthians");
insert into clube (sq_clube,sq_pais,nm_clube) values (2,14,"Aston Villa");
insert into clube (sq_clube,sq_pais,nm_clube) values (110704,45,"Fútbol Club Barcelona “B”");
insert into clube (sq_clube,sq_pais,nm_clube) values (234,38,"Sport Lisboa Benfica");
insert into clube (sq_clube,sq_pais,nm_clube) values (32,21,"Bayer 04 Leverkusen");
insert into clube (sq_clube,sq_pais,nm_clube) values (7,14,"Everton");
insert into clube (sq_clube,sq_pais,nm_clube) values (65,18,"LOSC Lille");
insert into clube (sq_clube,sq_pais,nm_clube) values (1035,54,"Atlético Mineiro");
insert into clube (sq_clube,sq_pais,nm_clube) values (17,14,"Southampton");
insert into clube (sq_clube,sq_pais,nm_clube) values (1960,14,"Swansea City");
insert into clube (sq_clube,sq_pais,nm_clube) values (1819,18,"AS Saint-Etienne");
insert into clube (sq_clube,sq_pais,nm_clube) values (219,18,"Olympique de Marseille");
insert into clube (sq_clube,sq_pais,nm_clube) values (46,27,"Lazio");
insert into clube (sq_clube,sq_pais,nm_clube) values (481,45,"Sevilla Fútbol Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (15,14,"Queens Park Rangers");
insert into clube (sq_clube,sq_pais,nm_clube) values (1048,54,"Internacional");
insert into clube (sq_clube,sq_pais,nm_clube) values (247,34,"PSV");
insert into clube (sq_clube,sq_pais,nm_clube) values (448,45,"Athletic Club de Bilbao");
insert into clube (sq_clube,sq_pais,nm_clube) values (483,45,"Villarreal Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (110710,45,"Real Madrid Castilla");
insert into clube (sq_clube,sq_pais,nm_clube) values (28,21,"Hamburger SV");
insert into clube (sq_clube,sq_pais,nm_clube) values (100769,40,"Zenit St. Petersburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (38,21,"SV Werder Bremen");
insert into clube (sq_clube,sq_pais,nm_clube) values (567,54,"Fluminense");
insert into clube (sq_clube,sq_pais,nm_clube) values (175,21,"VfL Wolfsburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (55,27,"Udinese");
insert into clube (sq_clube,sq_pais,nm_clube) values (144,14,"Fulham");
insert into clube (sq_clube,sq_pais,nm_clube) values (106,14,"Sunderland");
insert into clube (sq_clube,sq_pais,nm_clube) values (23,21,"Borussia Mönchengladbach");
insert into clube (sq_clube,sq_pais,nm_clube) values (1043,54,"Flamengo");
insert into clube (sq_clube,sq_pais,nm_clube) values (315,40,"CSKA Moskva");
insert into clube (sq_clube,sq_pais,nm_clube) values (1629,54,"Grêmio");
insert into clube (sq_clube,sq_pais,nm_clube) values (100766,40,"Anzhi Makhachkala");
insert into clube (sq_clube,sq_pais,nm_clube) values (246,34,"Feyenoord");
insert into clube (sq_clube,sq_pais,nm_clube) values (1877,211,"Boca Juniors");
insert into clube (sq_clube,sq_pais,nm_clube) values (383,54,"P. São Paulo");
insert into clube (sq_clube,sq_pais,nm_clube) values (1879,83,"América");
insert into clube (sq_clube,sq_pais,nm_clube) values (19,14,"West Ham United");
insert into clube (sq_clube,sq_pais,nm_clube) values (1917,14,"Wigan Athletic");
insert into clube (sq_clube,sq_pais,nm_clube) values (36,21,"VfB Stuttgart");
insert into clube (sq_clube,sq_pais,nm_clube) values (229,7,"RSC Anderlecht");
insert into clube (sq_clube,sq_pais,nm_clube) values (1909,34,"Vitesse");
insert into clube (sq_clube,sq_pais,nm_clube) values (78,42,"Celtic");
insert into clube (sq_clube,sq_pais,nm_clube) values (109,14,"West Bromwich Albion");
insert into clube (sq_clube,sq_pais,nm_clube) values (1843,27,"Palermo");
insert into clube (sq_clube,sq_pais,nm_clube) values (449,45,"Real Betis Balompié");
insert into clube (sq_clube,sq_pais,nm_clube) values (50,27,"Parma");
insert into clube (sq_clube,sq_pais,nm_clube) values (1876,211,"River Plate");
insert into clube (sq_clube,sq_pais,nm_clube) values (485,21,"Hannover 96");
insert into clube (sq_clube,sq_pais,nm_clube) values (100767,40,"Spartak Moskva");
insert into clube (sq_clube,sq_pais,nm_clube) values (1806,14,"Stoke City");
insert into clube (sq_clube,sq_pais,nm_clube) values (166,21,"Hertha BSC Berlin");
insert into clube (sq_clube,sq_pais,nm_clube) values (1837,27,"Sampdoria");
insert into clube (sq_clube,sq_pais,nm_clube) values (4,14,"Bolton Wanderers");
insert into clube (sq_clube,sq_pais,nm_clube) values (1792,14,"Norwich City");
insert into clube (sq_clube,sq_pais,nm_clube) values (110556,27,"Genoa");
insert into clube (sq_clube,sq_pais,nm_clube) values (59,18,"Girondins de Bordeaux");
insert into clube (sq_clube,sq_pais,nm_clube) values (3,14,"Blackburn Rovers");
insert into clube (sq_clube,sq_pais,nm_clube) values (33,21,"1860 Munich");
insert into clube (sq_clube,sq_pais,nm_clube) values (568,54,"Cruzeiro");
insert into clube (sq_clube,sq_pais,nm_clube) values (896,47,"FC Basel 1893");
insert into clube (sq_clube,sq_pais,nm_clube) values (54,27,"Torino");
insert into clube (sq_clube,sq_pais,nm_clube) values (8,14,"Leeds United");
insert into clube (sq_clube,sq_pais,nm_clube) values (64,18,"Racing Club de Lens");
insert into clube (sq_clube,sq_pais,nm_clube) values (517,54,"Botafogo");
insert into clube (sq_clube,sq_pais,nm_clube) values (192,27,"Chievo Verona");
insert into clube (sq_clube,sq_pais,nm_clube) values (569,54,"V. Rio de Janeiro");
insert into clube (sq_clube,sq_pais,nm_clube) values (697,95,"Los Angeles Galaxy");
insert into clube (sq_clube,sq_pais,nm_clube) values (110,14,"Wolverhampton Wanderers");
insert into clube (sq_clube,sq_pais,nm_clube) values (1842,27,"Cagliari");
insert into clube (sq_clube,sq_pais,nm_clube) values (689,95,"New York Red Bulls");
insert into clube (sq_clube,sq_pais,nm_clube) values (189,27,"Bologna");
insert into clube (sq_clube,sq_pais,nm_clube) values (10029,21,"1899 Hoffenheim");
insert into clube (sq_clube,sq_pais,nm_clube) values (232,7,"Standard Liège");
insert into clube (sq_clube,sq_pais,nm_clube) values (280,211,"Olympiakos CFP");
insert into clube (sq_clube,sq_pais,nm_clube) values (39,27,"Atalanta");
insert into clube (sq_clube,sq_pais,nm_clube) values (1799,14,"Crystal Palace");
insert into clube (sq_clube,sq_pais,nm_clube) values (1961,14,"Cardiff City");
insert into clube (sq_clube,sq_pais,nm_clube) values (88,14,"Birmingham City");
insert into clube (sq_clube,sq_pais,nm_clube) values (74,18,"Stade Rennais FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1824,21,"Eintracht Frankfurt");
insert into clube (sq_clube,sq_pais,nm_clube) values (242,45,"Real Club Deportivo de La Coruña");
insert into clube (sq_clube,sq_pais,nm_clube) values (72,18,"OGC Nice");
insert into clube (sq_clube,sq_pais,nm_clube) values (452,45,"RCD Espanyol de Barcelona");
insert into clube (sq_clube,sq_pais,nm_clube) values (1913,34,"sc Heerenveen");
insert into clube (sq_clube,sq_pais,nm_clube) values (1908,34,"FC Twente");
insert into clube (sq_clube,sq_pais,nm_clube) values (70,18,"Montpellier Hérault Sport Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (200,27,"Pescara");
insert into clube (sq_clube,sq_pais,nm_clube) values (121,14,"Crewe Alexandra");
insert into clube (sq_clube,sq_pais,nm_clube) values (1906,34,"AZ");
insert into clube (sq_clube,sq_pais,nm_clube) values (1809,18,"Toulouse FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (190,27,"Brescia");
insert into clube (sq_clube,sq_pais,nm_clube) values (1880,83,"Guadalajara");
insert into clube (sq_clube,sq_pais,nm_clube) values (86,211,"Rangers");
insert into clube (sq_clube,sq_pais,nm_clube) values (1860,45,"Getafe Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (1893,38,"C. Funchal");
insert into clube (sq_clube,sq_pais,nm_clube) values (57,18,"AJ Auxerre");
insert into clube (sq_clube,sq_pais,nm_clube) values (110364,27,"Catania");
insert into clube (sq_clube,sq_pais,nm_clube) values (312,40,"Dinamo Moskva");
insert into clube (sq_clube,sq_pais,nm_clube) values (1793,14,"Reading");
insert into clube (sq_clube,sq_pais,nm_clube) values (171,21,"1. FC Nuremberg");
insert into clube (sq_clube,sq_pais,nm_clube) values (217,18,"Lorient Bretagne Sud");
insert into clube (sq_clube,sq_pais,nm_clube) values (1871,37,"L. Warszawa");
insert into clube (sq_clube,sq_pais,nm_clube) values (450,45,"Real Club Celta de Vigo");
insert into clube (sq_clube,sq_pais,nm_clube) values (1790,14,"Portsmouth");
insert into clube (sq_clube,sq_pais,nm_clube) values (31,21,"1. FC Köln");
insert into clube (sq_clube,sq_pais,nm_clube) values (169,21,"1. FSV Mainz 05");
insert into clube (sq_clube,sq_pais,nm_clube) values (206,27,"H. Verona");
insert into clube (sq_clube,sq_pais,nm_clube) values (14,14,"Nottingham Forest");
insert into clube (sq_clube,sq_pais,nm_clube) values (1884,211,"Panathinaikos FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (95,14,"Leicester City");
insert into clube (sq_clube,sq_pais,nm_clube) values (1952,14,"Hull City");
insert into clube (sq_clube,sq_pais,nm_clube) values (480,45,"Rayo Vallecano de Madrid");
insert into clube (sq_clube,sq_pais,nm_clube) values (873,37,"L. Poznań");
insert into clube (sq_clube,sq_pais,nm_clube) values (1878,83,"Cruz Azul");
insert into clube (sq_clube,sq_pais,nm_clube) values (819,13,"FC København");
insert into clube (sq_clube,sq_pais,nm_clube) values (453,45,"Real Club Deportivo Mallorca");
insert into clube (sq_clube,sq_pais,nm_clube) values (231,7,"Club Brugge KV");
insert into clube (sq_clube,sq_pais,nm_clube) values (1887,38,"Vitória de Guimarães");
insert into clube (sq_clube,sq_pais,nm_clube) values (1926,14,"Blackpool");
insert into clube (sq_clube,sq_pais,nm_clube) values (25,21,"SC Freiburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (110227,40,"Rubin Kazan");
insert into clube (sq_clube,sq_pais,nm_clube) values (244,45,"Real Zaragoza");
insert into clube (sq_clube,sq_pais,nm_clube) values (1032,83,"Monterrey");
insert into clube (sq_clube,sq_pais,nm_clube) values (1896,38,"SC Braga");
insert into clube (sq_clube,sq_pais,nm_clube) values (111144,95,"Seattle Sounders FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1794,14,"Sheffield United");
insert into clube (sq_clube,sq_pais,nm_clube) values (1804,14,"Bradford City");
insert into clube (sq_clube,sq_pais,nm_clube) values (1808,14,"Brighton & Hove Albion");
insert into clube (sq_clube,sq_pais,nm_clube) values (982,167,"FC Seoul");
insert into clube (sq_clube,sq_pais,nm_clube) values (1738,18,"Le Havre Athletic Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (1861,45,"Unión Deportiva Almería");
insert into clube (sq_clube,sq_pais,nm_clube) values (12,14,"Middlesbrough");
insert into clube (sq_clube,sq_pais,nm_clube) values (1970,83,"Tigres U.A.N.L.");
insert into clube (sq_clube,sq_pais,nm_clube) values (29,21,"1. FC Kaiserslautern");
insert into clube (sq_clube,sq_pais,nm_clube) values (191,4,"Red Bull Salzburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (393,211,"PAOK");
insert into clube (sq_clube,sq_pais,nm_clube) values (58,18,"Sporting Club Bastia");
insert into clube (sq_clube,sq_pais,nm_clube) values (1795,14,"Watford");
insert into clube (sq_clube,sq_pais,nm_clube) values (160,21,"VfL Bochum 1848");
insert into clube (sq_clube,sq_pais,nm_clube) values (1853,45,"Levante Unión Deportiva");
insert into clube (sq_clube,sq_pais,nm_clube) values (226,18,"FC Sochaux-Montbéliard");
insert into clube (sq_clube,sq_pais,nm_clube) values (1477,167,"Jeonbuk Hyundai Motors");
insert into clube (sq_clube,sq_pais,nm_clube) values (127,14,"Shrewsbury");
insert into clube (sq_clube,sq_pais,nm_clube) values (479,45,"Club Atlético Osasuna");
insert into clube (sq_clube,sq_pais,nm_clube) values (278,211,"AEK Athens");
insert into clube (sq_clube,sq_pais,nm_clube) values (15005,7,"Sv Zulte-Waregem");
insert into clube (sq_clube,sq_pais,nm_clube) values (165,21,"SpVgg Greuther Fürth");
insert into clube (sq_clube,sq_pais,nm_clube) values (1844,27,"Livorno");
insert into clube (sq_clube,sq_pais,nm_clube) values (111397,195,"Melbourne Victory FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (456,45,"Real Racing Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (91,14,"Derby County");
insert into clube (sq_clube,sq_pais,nm_clube) values (111974,27,"Sassuolo");
insert into clube (sq_clube,sq_pais,nm_clube) values (100765,40,"Lokomotiv Moskva");
insert into clube (sq_clube,sq_pais,nm_clube) values (1929,14,"Plymouth Argyle");
insert into clube (sq_clube,sq_pais,nm_clube) values (1838,27,"Siena");
insert into clube (sq_clube,sq_pais,nm_clube) values (322,47,"Grasshopper-Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (89,14,"Charlton Athletic");
insert into clube (sq_clube,sq_pais,nm_clube) values (673,7,"KRC Genk");
insert into clube (sq_clube,sq_pais,nm_clube) values (111044,54,"Coritiba");
insert into clube (sq_clube,sq_pais,nm_clube) values (71,18,"FC Nantes");
insert into clube (sq_clube,sq_pais,nm_clube) values (1739,18,"Le Mans FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110636,21,"Fortuna Düsseldorf");
insert into clube (sq_clube,sq_pais,nm_clube) values (688,95,"D.C. United");
insert into clube (sq_clube,sq_pais,nm_clube) values (110929,211,"Kaizer Chiefs");
insert into clube (sq_clube,sq_pais,nm_clube) values (111070,95,"Club Deportivo Chivas USA");
insert into clube (sq_clube,sq_pais,nm_clube) values (1873,37,"W. Kraków");
insert into clube (sq_clube,sq_pais,nm_clube) values (298,36,"Rosenborg BK");
insert into clube (sq_clube,sq_pais,nm_clube) values (1796,14,"Burnley");
insert into clube (sq_clube,sq_pais,nm_clube) values (462,45,"Real Valladolid Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (94,14,"Ipswich Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (1823,18,"AS Nancy Lorraine");
insert into clube (sq_clube,sq_pais,nm_clube) values (110832,45,"Granada Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (894,47,"FC Zürich");
insert into clube (sq_clube,sq_pais,nm_clube) values (135,14,"Barnet");
insert into clube (sq_clube,sq_pais,nm_clube) values (142,14,"Doncaster Rovers");
insert into clube (sq_clube,sq_pais,nm_clube) values (1930,14,"Northampton Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (1807,14,"Sheffield Wednesday");
insert into clube (sq_clube,sq_pais,nm_clube) values (110456,18,"Valenciennes FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (97,14,"Milwall");
insert into clube (sq_clube,sq_pais,nm_clube) values (696,95,"Sporting Kansas City");
insert into clube (sq_clube,sq_pais,nm_clube) values (687,95,"Columbus Crew");
insert into clube (sq_clube,sq_pais,nm_clube) values (1746,27,"Empoli");
insert into clube (sq_clube,sq_pais,nm_clube) values (111132,25,"UCD AFC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110147,83,"Pachuca");
insert into clube (sq_clube,sq_pais,nm_clube) values (256,4,"FK Austria Wien");
insert into clube (sq_clube,sq_pais,nm_clube) values (1028,83,"Monarcas Morelia");
insert into clube (sq_clube,sq_pais,nm_clube) values (320,46,"Malmö FF");
insert into clube (sq_clube,sq_pais,nm_clube) values (100409,21,"FC Augsburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (744,38,"Rio Ave FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (101085,211,"Racing Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (1797,14,"Rotherham United");
insert into clube (sq_clube,sq_pais,nm_clube) values (110930,211,"Orlando Pirates");
insert into clube (sq_clube,sq_pais,nm_clube) values (614,18,"AC Ajaccio");
insert into clube (sq_clube,sq_pais,nm_clube) values (111400,195,"Sydney FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (459,45,"Real Sporting de Gijón");
insert into clube (sq_clube,sq_pais,nm_clube) values (209,4,"SK Sturm Graz");
insert into clube (sq_clube,sq_pais,nm_clube) values (1962,14,"Bristol Rovers");
insert into clube (sq_clube,sq_pais,nm_clube) values (468,45,"Elche Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (417,36,"Molde FK");
insert into clube (sq_clube,sq_pais,nm_clube) values (2056,167,"Daegu FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1903,34,"FC Utrecht");
insert into clube (sq_clube,sq_pais,nm_clube) values (691,95,"New England Revolution");
insert into clube (sq_clube,sq_pais,nm_clube) values (81,42,"Hibernian");
insert into clube (sq_clube,sq_pais,nm_clube) values (900,47,"BSC Young Boys");
insert into clube (sq_clube,sq_pais,nm_clube) values (1881,83,"U.N.A.M.");
insert into clube (sq_clube,sq_pais,nm_clube) values (254,4,"SK Rapid Wien");
insert into clube (sq_clube,sq_pais,nm_clube) values (110915,27,"Cesena");
insert into clube (sq_clube,sq_pais,nm_clube) values (418,36,"Tromsø IL");
insert into clube (sq_clube,sq_pais,nm_clube) values (210,18,"Stade Malherbe Caen");
insert into clube (sq_clube,sq_pais,nm_clube) values (319,46,"IFK Göteborg");
insert into clube (sq_clube,sq_pais,nm_clube) values (1902,34,"Roda JC Kerkrade");
insert into clube (sq_clube,sq_pais,nm_clube) values (1901,38,"Académica Coimbra");
insert into clube (sq_clube,sq_pais,nm_clube) values (269,13,"Brøndby IF");
insert into clube (sq_clube,sq_pais,nm_clube) values (1934,14,"Swindon Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (1892,38,"Paços Ferreira");
insert into clube (sq_clube,sq_pais,nm_clube) values (378,18,"Stade Brestois 29");
insert into clube (sq_clube,sq_pais,nm_clube) values (1910,34,"N.E.C.");
insert into clube (sq_clube,sq_pais,nm_clube) values (1788,13,"FC Nordsjælland");
insert into clube (sq_clube,sq_pais,nm_clube) values (110089,40,"Kuban Krasnodar");
insert into clube (sq_clube,sq_pais,nm_clube) values (1915,34,"FC Groningen");
insert into clube (sq_clube,sq_pais,nm_clube) values (62,18,"En Avant de Guingamp");
insert into clube (sq_clube,sq_pais,nm_clube) values (1846,27,"Ascoli");
insert into clube (sq_clube,sq_pais,nm_clube) values (472,45,"Unión Deportiva Las Palmas");
insert into clube (sq_clube,sq_pais,nm_clube) values (301,37,"W. Łódź");
insert into clube (sq_clube,sq_pais,nm_clube) values (1848,27,"Bari");
insert into clube (sq_clube,sq_pais,nm_clube) values (143,14,"Exeter City");
insert into clube (sq_clube,sq_pais,nm_clube) values (162,21,"FC Energie Cottbus");
insert into clube (sq_clube,sq_pais,nm_clube) values (373,14,"Dagenham e Redbridge");
insert into clube (sq_clube,sq_pais,nm_clube) values (983,167,"Suwon Samsung Bluewings");
insert into clube (sq_clube,sq_pais,nm_clube) values (693,95,"Chicago Fire");
insert into clube (sq_clube,sq_pais,nm_clube) values (294,18,"ES Troyes AC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1570,37,"P. Warszawa");
insert into clube (sq_clube,sq_pais,nm_clube) values (1598,54,"Bahia");
insert into clube (sq_clube,sq_pais,nm_clube) values (110770,47,"FC Sion");
insert into clube (sq_clube,sq_pais,nm_clube) values (1951,14,"Oxford United FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1919,14,"Bristol City");
insert into clube (sq_clube,sq_pais,nm_clube) values (111678,83,"Tijuana");
insert into clube (sq_clube,sq_pais,nm_clube) values (111045,54,"Santa Catarina");
insert into clube (sq_clube,sq_pais,nm_clube) values (110329,21,"FC St. Pauli");
insert into clube (sq_clube,sq_pais,nm_clube) values (101112,95,"Vancouver Whitecaps FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (111065,95,"Real Salt Lake");
insert into clube (sq_clube,sq_pais,nm_clube) values (695,95,"FC Dallas");
insert into clube (sq_clube,sq_pais,nm_clube) values (1882,83,"Toluca");
insert into clube (sq_clube,sq_pais,nm_clube) values (101114,83,"Atlas");
insert into clube (sq_clube,sq_pais,nm_clube) values (1939,14,"Huddersfield Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (1802,14,"Gillingham");
insert into clube (sq_clube,sq_pais,nm_clube) values (920,36,"Vålerenga Fotball");
insert into clube (sq_clube,sq_pais,nm_clube) values (181,42,"Dundee United");
insert into clube (sq_clube,sq_pais,nm_clube) values (1943,14,"Bournemouth");
insert into clube (sq_clube,sq_pais,nm_clube) values (80,42,"Heart of Midlothian");
insert into clube (sq_clube,sq_pais,nm_clube) values (433,46,"AIK Fotboll");
insert into clube (sq_clube,sq_pais,nm_clube) values (111491,27,"Grosseto");
insert into clube (sq_clube,sq_pais,nm_clube) values (1798,14,"Milton Keynes Dons");
insert into clube (sq_clube,sq_pais,nm_clube) values (110144,83,"Santos Laguna");
insert into clube (sq_clube,sq_pais,nm_clube) values (1891,38,"CD Nacional");
insert into clube (sq_clube,sq_pais,nm_clube) values (111043,54,"Ponte Preta de Campinas");
insert into clube (sq_clube,sq_pais,nm_clube) values (1800,14,"Coventry City");
insert into clube (sq_clube,sq_pais,nm_clube) values (1933,14,"Wycombe Wanderers");
insert into clube (sq_clube,sq_pais,nm_clube) values (203,27,"Reggina");
insert into clube (sq_clube,sq_pais,nm_clube) values (111398,195,"Newcastle United Jets FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1473,167,"Ulsan Hyundai Horang-i");
insert into clube (sq_clube,sq_pais,nm_clube) values (110313,14,"Accrington Stanley");
insert into clube (sq_clube,sq_pais,nm_clube) values (1801,14,"Preston North End");
insert into clube (sq_clube,sq_pais,nm_clube) values (100879,45,"Hércules Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (112260,14,"Fleetwood Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (379,18,"Stade de Reims");
insert into clube (sq_clube,sq_pais,nm_clube) values (111651,95,"Toronto FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (420,37,"G. Zabrze");
insert into clube (sq_clube,sq_pais,nm_clube) values (111050,54,"N.Recife");
insert into clube (sq_clube,sq_pais,nm_clube) values (110151,83,"Jaguares de Chiapas");
insert into clube (sq_clube,sq_pais,nm_clube) values (101116,83,"Atlante");
insert into clube (sq_clube,sq_pais,nm_clube) values (1744,27,"Modena");
insert into clube (sq_clube,sq_pais,nm_clube) values (674,7,"KAA Gent");
insert into clube (sq_clube,sq_pais,nm_clube) values (1937,14,"Notts County");
insert into clube (sq_clube,sq_pais,nm_clube) values (111091,37,"Gdańsk");
insert into clube (sq_clube,sq_pais,nm_clube) values (675,7,"Beerschot AC");
insert into clube (sq_clube,sq_pais,nm_clube) values (111271,18,"Evian Thonon Gaillard FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (299,36,"Lillestrøm SK");
insert into clube (sq_clube,sq_pais,nm_clube) values (1920,14,"Oldham Athletic");
insert into clube (sq_clube,sq_pais,nm_clube) values (1825,21,"MSV Duisburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (305,25,"Bohemians FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110109,40,"Terek Grozny");
insert into clube (sq_clube,sq_pais,nm_clube) values (111396,195,"Central Coast Mariners FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (306,25,"Shamrock Rovers");
insert into clube (sq_clube,sq_pais,nm_clube) values (112119,54,"A. Goiânia");
insert into clube (sq_clube,sq_pais,nm_clube) values (613,18,"CS Sedan Ardennes");
insert into clube (sq_clube,sq_pais,nm_clube) values (665,38,"Vitória de Setúbal");
insert into clube (sq_clube,sq_pais,nm_clube) values (112398,27,"Vercelli");
insert into clube (sq_clube,sq_pais,nm_clube) values (1948,14,"York City");
insert into clube (sq_clube,sq_pais,nm_clube) values (1928,14,"Port Vale");
insert into clube (sq_clube,sq_pais,nm_clube) values (650,34,"ADO Den Haag");
insert into clube (sq_clube,sq_pais,nm_clube) values (346,14,"Yeovil Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (1938,14,"Peterborough United");
insert into clube (sq_clube,sq_pais,nm_clube) values (698,95,"Houston Dynamo");
insert into clube (sq_clube,sq_pais,nm_clube) values (111057,54,"S.Pernambuco");
insert into clube (sq_clube,sq_pais,nm_clube) values (110724,7,"KV Mechelen");
insert into clube (sq_clube,sq_pais,nm_clube) values (1932,14,"Barnsley");
insert into clube (sq_clube,sq_pais,nm_clube) values (112225,27,"Novara");
insert into clube (sq_clube,sq_pais,nm_clube) values (694,95,"Colorado Rapids");
insert into clube (sq_clube,sq_pais,nm_clube) values (571,45,"Real Club Recreativo de Huelva");
insert into clube (sq_clube,sq_pais,nm_clube) values (111928,95,"San Jose Earthquakes");
insert into clube (sq_clube,sq_pais,nm_clube) values (432,46,"Helsingborg IF");
insert into clube (sq_clube,sq_pais,nm_clube) values (1924,14,"Chesterfield");
insert into clube (sq_clube,sq_pais,nm_clube) values (110912,27,"Padua");
insert into clube (sq_clube,sq_pais,nm_clube) values (2007,7,"Sporting Lokeren");
insert into clube (sq_clube,sq_pais,nm_clube) values (111139,95,"Montreal Impact");
insert into clube (sq_clube,sq_pais,nm_clube) values (111083,37,"Kielce");
insert into clube (sq_clube,sq_pais,nm_clube) values (1475,167,"Chunnam Dragons");
insert into clube (sq_clube,sq_pais,nm_clube) values (710,46,"Djurgårdens IF");
insert into clube (sq_clube,sq_pais,nm_clube) values (110749,37,"Lubin");
insert into clube (sq_clube,sq_pais,nm_clube) values (1904,34,"NAC Breda");
insert into clube (sq_clube,sq_pais,nm_clube) values (1867,45,"Córdoba Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (874,37,"R. Chorzów");
insert into clube (sq_clube,sq_pais,nm_clube) values (700,46,"IF Elfsborg");
insert into clube (sq_clube,sq_pais,nm_clube) values (111140,95,"Portland Timbers");
insert into clube (sq_clube,sq_pais,nm_clube) values (382,14,"Aldershot Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (77,42,"Aberdeen");
insert into clube (sq_clube,sq_pais,nm_clube) values (357,14,"Morecambe");
insert into clube (sq_clube,sq_pais,nm_clube) values (112259,14,"AFC Wimbledon");
insert into clube (sq_clube,sq_pais,nm_clube) values (1925,14,"Brentford");
insert into clube (sq_clube,sq_pais,nm_clube) values (1935,14,"Colchester Untied");
insert into clube (sq_clube,sq_pais,nm_clube) values (980,167,"Daejeon Citizen");
insert into clube (sq_clube,sq_pais,nm_clube) values (1855,45,"Real Murcia Club de Fútbol");
insert into clube (sq_clube,sq_pais,nm_clube) values (1907,34,"Willem II");
insert into clube (sq_clube,sq_pais,nm_clube) values (1474,167,"Pohang Steelers");
insert into clube (sq_clube,sq_pais,nm_clube) values (110149,83,"San Luis");
insert into clube (sq_clube,sq_pais,nm_clube) values (10030,21,"SC Paderborn 07");
insert into clube (sq_clube,sq_pais,nm_clube) values (110745,37,"J. Białystok");
insert into clube (sq_clube,sq_pais,nm_clube) values (1955,14,"Rochdale");
insert into clube (sq_clube,sq_pais,nm_clube) values (477,45,"Club Deportivo Numancia de Soria");
insert into clube (sq_clube,sq_pais,nm_clube) values (212,18,"La Berrichonne de Châteauroux");
insert into clube (sq_clube,sq_pais,nm_clube) values (1831,21,"1. FC Union Berlin");
insert into clube (sq_clube,sq_pais,nm_clube) values (503,21,"SG Dynamo Dresden");
insert into clube (sq_clube,sq_pais,nm_clube) values (605,183,"Al-Hilal Saudi FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1936,14,"Cheltenham Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (100651,34,"VVV-Venlo");
insert into clube (sq_clube,sq_pais,nm_clube) values (1954,14,"Southend United");
insert into clube (sq_clube,sq_pais,nm_clube) values (838,25,"Bray Wanderers");
insert into clube (sq_clube,sq_pais,nm_clube) values (112237,27,"Varese");
insert into clube (sq_clube,sq_pais,nm_clube) values (670,7,"Sporting Charleroi");
insert into clube (sq_clube,sq_pais,nm_clube) values (111993,27,"Cittadella");
insert into clube (sq_clube,sq_pais,nm_clube) values (423,25,"St. Patrick's Athletic");
insert into clube (sq_clube,sq_pais,nm_clube) values (100634,34,"Heracles Almelo");
insert into clube (sq_clube,sq_pais,nm_clube) values (111399,195,"Perth Glory FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (919,36,"SK Brann");
insert into clube (sq_clube,sq_pais,nm_clube) values (110744,37,"G. Bełchatów");
insert into clube (sq_clube,sq_pais,nm_clube) values (111588,167,"GyeongNam FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110569,18,"Dijon FCO");
insert into clube (sq_clube,sq_pais,nm_clube) values (1905,34,"RKC Waalwijk");
insert into clube (sq_clube,sq_pais,nm_clube) values (898,47,"FC St. Gallen");
insert into clube (sq_clube,sq_pais,nm_clube) values (111092,37,"Wrocław");
insert into clube (sq_clube,sq_pais,nm_clube) values (111674,183,"Al-Shabab");
insert into clube (sq_clube,sq_pais,nm_clube) values (112134,95,"Philadelphia Union");
insert into clube (sq_clube,sq_pais,nm_clube) values (1949,14,"Scunthorpe United");
insert into clube (sq_clube,sq_pais,nm_clube) values (1742,45,"Xerez Club Deportivo");
insert into clube (sq_clube,sq_pais,nm_clube) values (110741,27,"La Spezia");
insert into clube (sq_clube,sq_pais,nm_clube) values (1755,36,"Aalesunds FK");
insert into clube (sq_clube,sq_pais,nm_clube) values (100764,40,"Krylya Sovetov Samara");
insert into clube (sq_clube,sq_pais,nm_clube) values (1480,14,"Carlisle United");
insert into clube (sq_clube,sq_pais,nm_clube) values (917,36,"Stabæk Fotball");
insert into clube (sq_clube,sq_pais,nm_clube) values (922,36,"Strømsgodset IF");
insert into clube (sq_clube,sq_pais,nm_clube) values (1862,47,"FC Lausanne-Sport");
insert into clube (sq_clube,sq_pais,nm_clube) values (112124,27,"Castellammare di Stabia");
insert into clube (sq_clube,sq_pais,nm_clube) values (100805,42,"St. Mirren");
insert into clube (sq_clube,sq_pais,nm_clube) values (820,13,"Aalborg BK");
insert into clube (sq_clube,sq_pais,nm_clube) values (110734,27,"Crotone");
insert into clube (sq_clube,sq_pais,nm_clube) values (110062,45,"Girona Fútbol Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (111393,195,"Adelaide United FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110150,83,"Querétaro");
insert into clube (sq_clube,sq_pais,nm_clube) values (1847,27,"Vicenza");
insert into clube (sq_clube,sq_pais,nm_clube) values (100831,45,"Agrupación Deportiva Alcorcón");
insert into clube (sq_clube,sq_pais,nm_clube) values (110152,83,"Puebla");
insert into clube (sq_clube,sq_pais,nm_clube) values (711,46,"BK Häcken");
insert into clube (sq_clube,sq_pais,nm_clube) values (1945,14,"Bury");
insert into clube (sq_clube,sq_pais,nm_clube) values (15015,14,"Burton Albion");
insert into clube (sq_clube,sq_pais,nm_clube) values (110500,21,"Eintracht Braunschweig");
insert into clube (sq_clube,sq_pais,nm_clube) values (111594,46,"GAIS");
insert into clube (sq_clube,sq_pais,nm_clube) values (111766,195,"Wellington Phoenix FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (111989,18,"AC Arles Avignon");
insert into clube (sq_clube,sq_pais,nm_clube) values (1941,14,"Hartlepool United");
insert into clube (sq_clube,sq_pais,nm_clube) values (1530,18,"Angers SCO");
insert into clube (sq_clube,sq_pais,nm_clube) values (111395,195,"Brisbane Roar FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1815,18,"Clermont Foot Auvergne 63");
insert into clube (sq_clube,sq_pais,nm_clube) values (15048,14,"Tranmere Rovers");
insert into clube (sq_clube,sq_pais,nm_clube) values (300,36,"Viking FK");
insert into clube (sq_clube,sq_pais,nm_clube) values (1803,14,"Walsall");
insert into clube (sq_clube,sq_pais,nm_clube) values (111292,54,"Portuguesa");
insert into clube (sq_clube,sq_pais,nm_clube) values (110781,83,"Club León");
insert into clube (sq_clube,sq_pais,nm_clube) values (83,42,"Motherwell");
insert into clube (sq_clube,sq_pais,nm_clube) values (111239,21,"FC Ingolstadt 04");
insert into clube (sq_clube,sq_pais,nm_clube) values (1447,13,"SønderjyskE");
insert into clube (sq_clube,sq_pais,nm_clube) values (1572,25,"Drogheda United");
insert into clube (sq_clube,sq_pais,nm_clube) values (705,46,"Örebro SK");
insert into clube (sq_clube,sq_pais,nm_clube) values (2045,4,"FC Wacker Innsbruck");
insert into clube (sq_clube,sq_pais,nm_clube) values (111540,38,"S.C. Olhanense");
insert into clube (sq_clube,sq_pais,nm_clube) values (1750,7,"KSV Cercle-Brugge");
insert into clube (sq_clube,sq_pais,nm_clube) values (1516,13,"FC Midtjylland");
insert into clube (sq_clube,sq_pais,nm_clube) values (111821,4,"FC Admira Wacker Mödling");
insert into clube (sq_clube,sq_pais,nm_clube) values (1478,167,"Jeju United FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (112218,40,"FC Krasnodar");
insert into clube (sq_clube,sq_pais,nm_clube) values (445,25,"Derry City");
insert into clube (sq_clube,sq_pais,nm_clube) values (1476,167,"Busan I'Park");
insert into clube (sq_clube,sq_pais,nm_clube) values (100081,7,"KV Kortrijk");
insert into clube (sq_clube,sq_pais,nm_clube) values (1446,13,"AC Horsens");
insert into clube (sq_clube,sq_pais,nm_clube) values (1786,13,"Randers FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (272,13,"Odense Boldklub");
insert into clube (sq_clube,sq_pais,nm_clube) values (112020,27,"Lanciano");
insert into clube (sq_clube,sq_pais,nm_clube) values (10020,38,"Estoril");
insert into clube (sq_clube,sq_pais,nm_clube) values (112387,183,"Al-Ahli Saudi FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (239,7,"Lierse SK");
insert into clube (sq_clube,sq_pais,nm_clube) values (110230,40,"Alaniya Vladikavkaz");
insert into clube (sq_clube,sq_pais,nm_clube) values (1946,14,"Torquay United");
insert into clube (sq_clube,sq_pais,nm_clube) values (981,167,"Songnam Ilhwa Chunma");
insert into clube (sq_clube,sq_pais,nm_clube) values (110231,40,"FC Rostov");
insert into clube (sq_clube,sq_pais,nm_clube) values (1897,38,"SC Beira Mar");
insert into clube (sq_clube,sq_pais,nm_clube) values (897,47,"FC Luzern");
insert into clube (sq_clube,sq_pais,nm_clube) values (1715,47,"FC Thun");
insert into clube (sq_clube,sq_pais,nm_clube) values (506,21,"FC Erzgebirge Aue");
insert into clube (sq_clube,sq_pais,nm_clube) values (15021,45,"CE Sabadell FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (82,42,"Kilmarnock");
insert into clube (sq_clube,sq_pais,nm_clube) values (110326,18,"Tours FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1958,14,"Leyton Orient");
insert into clube (sq_clube,sq_pais,nm_clube) values (780,4,"SV Josko Ried");
insert into clube (sq_clube,sq_pais,nm_clube) values (1888,38,"V. Barcelos");
insert into clube (sq_clube,sq_pais,nm_clube) values (270,13,"Silkeborg IF");
insert into clube (sq_clube,sq_pais,nm_clube) values (112224,195,"Melbourne Heart FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1445,13,"Esbjerg fB");
insert into clube (sq_clube,sq_pais,nm_clube) values (110890,14,"Crawley Town");
insert into clube (sq_clube,sq_pais,nm_clube) values (224,18,"Nîmes Olympique");
insert into clube (sq_clube,sq_pais,nm_clube) values (110839,45,"Sociedad Deportiva Huesca");
insert into clube (sq_clube,sq_pais,nm_clube) values (1900,38,"Moreira de Cónegos");
insert into clube (sq_clube,sq_pais,nm_clube) values (563,25,"Sligo Rovers");
insert into clube (sq_clube,sq_pais,nm_clube) values (110765,167,"Incheon United FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (2023,45,"Sociedad Deportiva Ponferradina");
insert into clube (sq_clube,sq_pais,nm_clube) values (1439,46,"Kalmar FF");
insert into clube (sq_clube,sq_pais,nm_clube) values (271,13,"Aarhus GF");
insert into clube (sq_clube,sq_pais,nm_clube) values (100804,42,"St. Johnstone FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (111373,4,"SC Wiener Neustadt");
insert into clube (sq_clube,sq_pais,nm_clube) values (1785,4,"SV Mattersburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (110596,21,"FSV Frankfurt 1899");
insert into clube (sq_clube,sq_pais,nm_clube) values (110234,40,"Amkar Perm");
insert into clube (sq_clube,sq_pais,nm_clube) values (1820,18,"FC Istres Ouest Provence");
insert into clube (sq_clube,sq_pais,nm_clube) values (2041,36,"Fredrikstad FK");
insert into clube (sq_clube,sq_pais,nm_clube) values (422,25,"Cork City");
insert into clube (sq_clube,sq_pais,nm_clube) values (111086,37,"Gliwice");
insert into clube (sq_clube,sq_pais,nm_clube) values (2055,167,"SangJu Sangmu Phoenix FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (111277,46,"Gefle IF");
insert into clube (sq_clube,sq_pais,nm_clube) values (111087,37,"Bielsko-Biała");
insert into clube (sq_clube,sq_pais,nm_clube) values (620,42,"Inverness Caledonian Thistle");
insert into clube (sq_clube,sq_pais,nm_clube) values (324,47,"Servette FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (111827,45,"Club Deportivo Guadalajara");
insert into clube (sq_clube,sq_pais,nm_clube) values (702,46,"IFK Norrkoping");
insert into clube (sq_clube,sq_pais,nm_clube) values (361,14,"Stevenage");
insert into clube (sq_clube,sq_pais,nm_clube) values (1814,18,"Stade Lavallois Mayenne FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (570,27,"Terni");
insert into clube (sq_clube,sq_pais,nm_clube) values (112427,195,"Western Sydney Wanderers FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (112115,167,"Gangwon FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1914,34,"PEC Zwolle");
insert into clube (sq_clube,sq_pais,nm_clube) values (837,25,"Dundalk");
insert into clube (sq_clube,sq_pais,nm_clube) values (110069,45,"Club Deportivo Mirandés");
insert into clube (sq_clube,sq_pais,nm_clube) values (607,183,"Ittihad FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (112139,183,"Al Nassr FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1813,18,"Chamois Niortais FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1747,7,"RAEC Mons");
insert into clube (sq_clube,sq_pais,nm_clube) values (112217,40,"Volga Nizhny Novgorod");
insert into clube (sq_clube,sq_pais,nm_clube) values (1841,36,"Hønefoss BK");
insert into clube (sq_clube,sq_pais,nm_clube) values (112408,183,"Al Wehdah Club");
insert into clube (sq_clube,sq_pais,nm_clube) values (112392,183,"Al-Raed FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110746,37,"Szczecin");
insert into clube (sq_clube,sq_pais,nm_clube) values (100087,7,"Oud-Heverlee Leuven");
insert into clube (sq_clube,sq_pais,nm_clube) values (110316,18,"Gazélec FC Ajaccio");
insert into clube (sq_clube,sq_pais,nm_clube) values (110831,45,"Club Deportivo Lugo");
insert into clube (sq_clube,sq_pais,nm_clube) values (112072,46,"Mjällby AIF");
insert into clube (sq_clube,sq_pais,nm_clube) values (111835,46,"Åtvidabergs FF");
insert into clube (sq_clube,sq_pais,nm_clube) values (112374,36,"Sandnes Ulf");
insert into clube (sq_clube,sq_pais,nm_clube) values (1463,36,"FK Haugesund");
insert into clube (sq_clube,sq_pais,nm_clube) values (543,21,"SSV Jahn Regensburg");
insert into clube (sq_clube,sq_pais,nm_clube) values (112267,46,"Syrianska");
insert into clube (sq_clube,sq_pais,nm_clube) values (110106,40,"Mordovia Saransk");
insert into clube (sq_clube,sq_pais,nm_clube) values (1456,36,"Odd Grenland");
insert into clube (sq_clube,sq_pais,nm_clube) values (112390,183,"Al-Fateh FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110913,7,"Waasland-Beveren");
insert into clube (sq_clube,sq_pais,nm_clube) values (112096,183,"Ettifaq FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (110178,21,"SV Sandhausen 1916");
insert into clube (sq_clube,sq_pais,nm_clube) values (112394,183,"Hajer FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (112407,183,"Alshoulla FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (834,25,"Shelbourne FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (550,21,"VfR Aalen");
insert into clube (sq_clube,sq_pais,nm_clube) values (1465,36,"Sogndal");
insert into clube (sq_clube,sq_pais,nm_clube) values (112395,183,"Najran FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (111822,4,"Wolfsberger AC");
insert into clube (sq_clube,sq_pais,nm_clube) values (112258,167,"GwangJu FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (180,42,"Dundee FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (631,42,"Ross County FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (112389,183,"Al-Faisaly FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (112393,183,"Al-Taawoun FC");
insert into clube (sq_clube,sq_pais,nm_clube) values (1596,46,"GIF Sundsvall");
