<link rel="stylesheet" type="text/css" href="/library/jquery-image-crop/css/imgareaselect-animated.css" />
<!-- scripts -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="/library/jquery-image-crop/js/jquery.imgareaselect.pack.js"></script>
<script type="text/javascript" src="/library/jquery-image-crop/js/script.js"></script>
<style>
    /*    a, a h1{
            font-family: Georgia, "Times New Roman", Times, serif;
            font-size: 1.2em;
            color: #645348;
            font-style: italic;
            text-decoration: none;
            font-weight: 100;
            padding: 10px;
        }
        body{
            font: 12px Arial,Tahoma,Helvetica,FreeSans,sans-serif;
            text-transform: inherit;
            color: #582A00;
            background: #E7EDEE;
            width: 100%;
            margin: 0;
            padding: 0;
        }*/
    .wrap{
        width: 100%;
        margin: 10px auto;
        padding: 10px 15px;
        background: white;
        border: 2px solid #DBDBDB;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        text-align: center;
        overflow: hidden;
    }
    img#formUploadPhotoJogadorAdmin{
        border: 0;
        border-radius: 3px;
        -webkit-box-shadow: 0px 2px 7px 0px rgba(0, 0, 0, .27);
        box-shadow: 0px 2px 7px 0px rgba(0, 0, 0, .27);
        margin-bottom: 30px;
        overflow: hidden;
    }
    /*    input[type="submit"]{
            border-radius: 10px;
            background-color: #61B3DE;
            border: 0;
            color: white;
            font-weight: bold;
            font-style: italic;
            padding: 6px 15px 5px;
            cursor: pointer;
        }*/
</style>
<div class="wrap">
    <img id="formUploadPhotoJogadorAdmin" style="display:none;"/>
    <form action="/jogador/uploadPhoto/ajax/true" method="post" enctype="multipart/form-data">
        <input id="btnUploadPhotoJogadorAdmin" type="file" accept="image/png" name="image" />
        <input type="submit" value="Enviar">
        <input type="hidden" id="x" name="x" />
        <input type="hidden" id="y" name="y" />
        <input type="hidden" id="w" name="w" />
        <input type="hidden" id="h" name="h" />
    </form>
</div>

<script type="text/javascript">

    $(document).ready(function() {

        Index.admin.formUploadPhotoJogadorAdmin = $('#formUploadPhotoJogadorAdmin');
//
//        $("#formUploadPhotoJogadorAdmin").validate({
//            errorClass: "help-inline",
//            submitHandler: function() {
//                if (confirm('Você tem certeza que deseja enviar a foto selecionada agora?')) {
//                    $.post(Index.admin.formUploadPhotoJogadorAdmin.attr('action'), Index.admin.formUploadPhotoJogadorAdmin.serialize(), function(response) {
//                        if (response.status === 'success') {
//                            Index.admin.gridJogadorAdmin.fnDraw(false);
//                        }
//                        Util.showMessageBox(response);
//                    }, 'json');
//                }
//            }
//        });


    });

</script>