<style type="text/css">
    .logo-selecao-150{
        width: 100px;
        height: 100px;
    }
</style>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Listar Todos Seleções</a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i class="icon-search"></i></a>
                </div>
            </div>

            <div class="row-fluid search-bar-nav">
                <div class="span12">
                    <form>
                        <input class="search" placeholder="Search..." type="text">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    Seleções
                </div>
                <div>
                    <table id="tabela" class="table table-striped table-condensed">
                        <thead>
                        <th>
                        <div>#</div>
                        </th>
                        <th>
                        <div>Nome</div>
                        </th>
                        <th>
                        <div>Pais</div>
                        </th>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#tabela').dataTable({
            "bProcessing": true,
            "bServerSide": true,
            "sPaginationType": "full_numbers",
            "bJQueryUI": false,
            "sAjaxSource": "/selecao/loadGridSearch/ajax/true/",
            "oLanguage": {
                "oPaginate": {
                    "sFirst": "Primeira",
                    "sPrevious": "Anterior",
                    "sNext": "Próxima",
                    "sLast": "Última"
                },
                "sSearch": "Filtrar:",
                "sLengthMenu": "_MENU_",
                "sZeroRecords": "Nenhuma seleção encontrada",
                "sInfo": "Visualizando _START_ até _END_ de _TOTAL_ seleções",
                "sInfoEmpty": "Visualizando 0 até 0 de 0 seleções",
                "sInfoFiltered": "(filtrado de _MAX_ seleções)"
            },
            "fnRowCallback": function(nRow, aData, iDisplayIndex) {
                $('td:eq(0)', nRow).html('<img class="logo-selecao-150" src="/img/selecoes/logos/' + aData[0] + '.png">');
                $('td:eq(4)', nRow).html(aData[4] + '<b> cm</b>');
                $('td:eq(5)', nRow).html(aData[5] + '<b> kg</b>');
            }
        });
    });
</script>