<?php
$js1 = array(
    array("library/jquery/jquery.min.js", false),
    array("library/validate/jquery.validate.pt-Br.js", false),
    array("js/util.js", false)
);

$js2 = array(
    array("library/plastique/javascripts/application.js", false)
);

use br\com\cf\library\core\cache\Cache;
?>

<!DOCTYPE html>
<html lang="pt-Br">
    <head>
        <title><?php print(CF_APP_NAME); ?></title>
        <meta charset="utf-8">
        <!-- Always force latest IE rendering engine or request Chrome Frame -->
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <link href="library/plastique/stylesheets/application.css" media="screen" rel="stylesheet" type="text/css" />

        <!--[if lt IE 9]>
        <script src="library/plastique/javascripts/html5shiv.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/excanvas.js" type="text/javascript"></script>
        <script src="library/plastique/javascripts/iefix.js" type="text/javascript"></script>
        <link href="library/plastique/stylesheets/iefix.css" media="screen" rel="stylesheet" type="text/css" />
        <![endif]-->

        <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <?php Cache::factory()->js($js1)->output()->clean(); ?>          

    </head>

    <body class="login">

        <div class="container">
            <div class="login-wrapper" style="margin-top: 120px">
                <div style="text-align: center">
                    <i class="logo-icon"><img src="img/fifa-logo-original.png"></i>
                </div>

                <div id="login-manager">

                    <div id="login" class="login-wrapper animated">
                        <form id="formAuthUsuario" method="post" action="/usuario/auth/ajax/true">
                            <div class="input-group">
                                <input type="text" placeholder="email" class="input-transparent" id="tx_email" name="tx_email">
                                <input type="password" placeholder="senha" class="input-transparent" id="tx_senha" name="tx_senha">
                            </div>
                            <button id="login-submit" type="submit" class="login-button">Entrar</button>
                        </form>
                    </div>

                    <!--                    <div id="register" class="login-wrapper animated" style="display: none;">
                                            <form action="http://beer2code.com/themes/plastique/pages/dashboard/stats.html">
                                                <div class="input-group">
                                                    <input type="text" placeholder="email" class="input-transparent" />
                                                    <input type="text" placeholder="first name" class="input-transparent"/>
                                                    <input type="text" placeholder="last name" class="input-transparent"/>
                                                    <input type="email" placeholder="confirm password" class="input-transparent"/>
                                                    <input type="password" placeholder="password" class="input-transparent"/>
                                                </div>
                                                <button id="register-submit" type="submit" class="login-button">Register</button>
                                            </form>
                                        </div>-->

                    <div id="forgot" class="login-wrapper animated" style="display: none;">
                        <form action="http://beer2code.com/themes/plastique/pages/dashboard/stats.html" method="get">
                            <div class="input-group">
                                <input type="text" placeholder="email" class="input-transparent" />
                            </div>
                            <button id="forgot-submit" type="submit" class="login-button">Recuperar Senha</button>
                        </form>
                    </div>

                    <div class="inner-well" style="text-align: center; margin: 20px 0;">
                        <a href="#" id="login-link" class="button mini rounded gray"><i class="icon-signin"></i> Entrar</a>
                        <!--<a href="#" id="register-link" class="button mini rounded gray"><i class="icon-plus"></i> Register</a>-->
                        <a href="#" id="forgot-link" class="button mini rounded gray"><i class="icon-question-sign"></i> Recuperar Senha</a>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <script type="text/javascript">

        !(function($) {
            'use strict'
            $(document).ready(function() {

                // Validacao do Formulario : Novo Produto
                var process = false;
                var formNew = $('#formAuthUsuario');
                var actionNew = formNew.attr('action');

                $("#formAuthUsuario").validate({
                    errorClass: "help-inline",
                    submitHandler: function() {
                        if (!process) {
                            process = true;
                            $.post(actionNew, formNew.serialize(), function(response) {
                                if (response.status === 'success') {
                                    window.location = response.url;
                                } else {
                                    Util.showMessageBox(response);
                                }
                                process = false;
                            }, 'json');
                        }
                    }
                });

            });

        })(jQuery);

    </script>

    <script type="text/html" id="template-notification">
        <div class="notification animated fadeInLeftMiddle fast{{ item.itemClass }}">
        <div class="left">
        <div style="background-image: url({{ item.imagePath }})" class="{{ item.imageClass }}"></div>
        </div>
        <div class="right">
        <div class="inner">{{ item.text }}</div>
        <div class="time">{{ item.time }}</div>
        </div>

        <i class="icon-remove-sign hide"></i>
        </div>
    </script>
    <script type="text/html" id="template-notifications">
        <div class="container">
        <div class="row" id="notifications-wrapper">
        <div id="notifications" class="{{ bootstrapPositionClass }} notifications animated">
        <div id="dismiss-all" class="dismiss-all button blue">Dismiss all</div>
        <div id="content">
        <div id="notes"></div>
        </div>
        </div>
        </div>
        </div>
    </script>

    <?php Cache::factory()->js($js2)->output()->clean(); ?>   

</html>