<script type="text/javascript" src="library/datatables/plugins/jquery.dataTables.columnFilter.js"></script>
<script type="text/javascript" src="library/datatables/plugins/jquery.dataTables.filteringDelay.js"></script>

<style type="text/css">
    .dataTables_filter{
        display: none;
    }
</style>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-user"></i> Usuários</a></li>
                        <li class="active"><a href="#"><i class="icon-list"></i> Listar Todos</a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i title="Pesquisa Avançada" id="bthSearchUsuarioAdmin" class="icon-search"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div id="rowSearchUsuarioAdmin" class="row-fluid hidden">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Pesquisa Avançada
                        <span class="pull-left">
                            <span class="options">
                                <a href="#"><i class="icon-search"></i></a>
                            </span>
                        </span>
                    </div>

                    <form class="fill-up">
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="padded">
                                    <div class="note pull-left">Nome Completo</div>
                                    <div id="filterListUsuarioAdmin-Nome" class="input"></div>
                                    <div class="note pull-left">Email</div>
                                    <div id="filterListUsuarioAdmin-Email" class="input"></div>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="padded">
                                    <div class="note pull-left">Nick Microsoft Live</div>
                                    <div id="filterListUsuarioAdmin-Nick" class="input input-medium"></div>
                                    <div class="note pull-left">Série</div>
                                    <div id="filterListUsuarioAdmin-Serie" class="hidden"></div>
                                    <div class="input input-small">
                                        <select id="filterSerieGridUsuarioAdmin" class="input-medium">
                                            <option value="" selected="selected">Todas</option>
                                            <?php foreach ($this->series as $serie) : ?>
                                                <option value="<?php print($serie->nm_serie); ?>"><?php print($serie->nm_serie); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="note pull-left">Equipe</div>
                                    <div id="filterListUsuarioAdmin-Equipe" class="input input-medium"></div>

                                </div>
                            </div>
                            <div class="span3">
                                <div class="padded">
                                    <div class="note pull-left">ID</div>
                                    <div id="filterListUsuarioAdmin-ID" class="input input-medium"></div>
                                    <div class="note pull-left">Perfil</div>
                                    <div id="filterListUsuarioAdmin-Perfil" class="hidden"></div>
                                    <div class="input">
                                        <select id="filterPerfilGridUsuarioAdmin" class="input-medium">
                                            <option value="" selected="selected">Todos</option>
                                            <option value="0">Comum</option>
                                            <option value="1">Administrador</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="button blue" type="submit">Pesquisar</button>
                            <button class="button" type="reset">Limpar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    <i class="icon-user"></i> Usuários
                </div>
                <div>
                    <table id="gridUsers" class="table table-striped table-condensed">
                        <thead>
                        <th>
                        <div>#</div>
                        </th>
                        <th>
                        <div>N. Completo</div>
                        </th>
                        <th>
                        <div>Email</div>
                        </th>
                        <th>
                        <div>Nick</div>
                        </th>
                        <th>
                        <div>Série</div>
                        </th>
                        <th>
                        <div>Equipe</div>
                        </th>
                        <th>
                        <div>Perfil</div>
                        </th>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
        <?php print br\com\cf\library\core\view\View::partials('footer'); ?>     
    </div>
</section>

<script type="text/javascript">

    $(document).ready(function() {

    $("#btnDetailUser").die('click').live('click', function() {
    Util.showModal('Informações Usuário', 'Editar', '/usuario/formEdit/id_usuario/' + $(this).attr('id_usuario'));
    });

    $('#bthSearchUsuarioAdmin').click(function() {
    Index.admin.btnSearchUsuarioAdminHiddenToggle = !Index.admin.btnSearchUsuarioAdminHiddenToggle;
    if (Index.admin.btnSearchUsuarioAdminHiddenToggle) {
    $('#rowSearchUsuarioAdmin').addClass('hidden');
    } else {
    $('#rowSearchUsuarioAdmin').removeClass('hidden');
    }
    });

    $('#filterPerfilGridUsuarioAdmin').change(function(){
    $('#filterListUsuarioAdmin-Perfil .text_filter').val($(this).val()).keyup();
    });

    $('#filterSerieGridUsuarioAdmin').change(function(){
    $('#filterListUsuarioAdmin-Serie .text_filter').val($(this).val()).keyup();
    });

    Index.global.gridUsers = $('#gridUsers').dataTable({
    bProcessing: true,
    bServerSide: true,
    sPaginationType: "full_numbers",
    bJQueryUI: false,
    sAjaxSource: "/usuario/loadGridSearch/ajax/true/",
    "aoColumnDefs": [
    {"sName": "equals", "aTargets": [0]},
    {"sName": "like", "aTargets": [1]},
    {"sName": "like", "aTargets": [2]},
    {"sName": "like", "aTargets": [3]},
    {"sName": "equals", "aTargets": [4]},
    {"sName": "like", "aTargets": [5]},
    {"sName": "equals", "aTargets": [6]}
    ],
    oLanguage: {
    "oPaginate": {
    "sFirst": "Primeira",
    "sPrevious": "Anterior",
    "sNext": "Próxima",
    "sLast": "Última"
    },
    "sSearch": "Filtrar:",
    "sLengthMenu": "_MENU_",
    "sZeroRecords": "Nenhum usuário encontrado",
    "sInfo": "Visualizando _START_ até _END_ de _TOTAL_ usuários",
    "sInfoEmpty": "Visualizando 0 até 0 de 0 jogadores",
    "sInfoFiltered": "(filtrado de _MAX_ jogadores)"
    },
    fnRowCallback: function(nRow, aData, iDisplayIndex) {
    $('td:eq(0)', nRow).html('<a title="Editar" id="btnDetailUser" id_usuario="' + aData[0] + '" href="#"><img class="mini-img-in-grid" src="https://avatar-ssl.xboxlive.com/avatar/' + aData[3] + '/avatarpic-l.png" /></a>');
    $('td:eq(6)', nRow).html(aData[6] === '1' ? '<strong>Administrador</strong>' : 'Comum');
    }
    }).columnFilter({
    sPlaceHolder: "head:before",
    aoColumns: [
    {sSelector: "#filterListUsuarioAdmin-ID",type: "number"},
    {sSelector: "#filterListUsuarioAdmin-Nome"},
    {sSelector: "#filterListUsuarioAdmin-Email"},
    {sSelector: "#filterListUsuarioAdmin-Nick"},
    {sSelector: "#filterListUsuarioAdmin-Serie"},
    {sSelector: "#filterListUsuarioAdmin-Equipe"},
    {sSelector: "#filterListUsuarioAdmin-Perfil"}
    ]}
    ).fnSetFilteringDelay(3);
    });
</script>