<script type="text/javascript" src="library/datatables/plugins/jquery.dataTables.columnFilter.js"></script>
<script type="text/javascript" src="library/datatables/plugins/jquery.dataTables.filteringDelay.js"></script>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-user"></i> Usuários</a></li>
                        <li class="active"><a href="#"><i class="icon-list"></i> Listar Todos</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    Usuários
                </div>
                <div>
                    <table id="gridUsers" class="table table-striped table-condensed">
                        <thead>
                        <th>
                        <div>#</div>
                        </th>
                        <th>
                        <div>N. Completo</div>
                        </th>
                        <th>
                        <div>Email</div>
                        </th>
                        <th>
                        <div>Nick</div>
                        </th>
                        <th>
                        <div>Perfil</div>
                        </th>
                        </thead>
                    </table>
                </div>
            </div>
        </div>

        <!--DEFINIR COMO PARTIALS FOOTERS-->
        <div class="row-fluid">
            <div class="span12">
                <div class="footer">
                    <div>2014 © Painel FIFA 2014</div>
                    <div>desenvolvido por <a href="https://nexussit.com.br">Nexuss</a></div>
                </div>
            </div>
        </div>
        <!--DEFINIR COMO PARTIALS FOOTERS-->

    </div>
</section>

<script type="text/javascript">

    $(document).ready(function() {

        $("#btnDetailUser").die('click').live('click', function() {
            Util.showModal('Informações Usuário', 'Editar', '/usuario/formEdit/id_usuario/' + $(this).attr('id_usuario'));
        });

        Index.global.gridUsers = $('#gridUsers').dataTable({
            bProcessing: true,
            bServerSide: true,
            sPaginationType: "full_numbers",
            bJQueryUI: false,
            sAjaxSource: "/usuario/loadGridSearch/ajax/true/",
            oLanguage: {
                "oPaginate": {
                    "sFirst": "Primeira",
                    "sPrevious": "Anterior",
                    "sNext": "Próxima",
                    "sLast": "Última"
                },
                "sSearch": "Filtrar:",
                "sLengthMenu": "_MENU_",
                "sZeroRecords": "Nenhum usuário encontrado",
                "sInfo": "Visualizando _START_ até _END_ de _TOTAL_ usuários",
                "sInfoEmpty": "Visualizando 0 até 0 de 0 jogadores",
                "sInfoFiltered": "(filtrado de _MAX_ jogadores)"
            },
            fnRowCallback: function(nRow, aData, iDisplayIndex) {
                $('td:eq(0)', nRow).html('<a title="Editar" id="btnDetailUser" id_usuario="' + aData[0] + '" href="#"><img class="avatar" src="https://avatar-ssl.xboxlive.com/avatar/' + aData[3] + '/avatarpic-l.png" /></a>');
                $('td:eq(4)', nRow).html(aData[4] === '1' ? '<strong>Administrador</strong>' : 'Comum');
            }
        }).fnSetFilteringDelay(3);
    });
</script>