<style type="text/css">

    ul.explorer1{ 
        padding: 5px; 
        margin: 0; 
        font-size: 10px;
    } 

    ul.explorer1 ul{ 
        padding: 0; 
        margin: 0 0 0 10px; 
    } 
    ul.explorer1 li a{ font-family: Arial; text-decoration: none; color: black; } 
    ul.explorer1 li a:hover{ color: blue; } 
    ul.explorer1 li{ list-style: none; background-image: url("/img/dotted.gif"); background-repeat: repeat-y; padding: 2px 0 2px 20px; text-indent: -19px; background-position: 9px 0; } 
    ul.explorer1 li::before{ content: url("/img/bullete.gif") " "; }


    .explorer-selected{
        font-weight: bold;
    }
</style>


ATIVAR/DESATIVAR TODOS<input type="checkbox" class="checkboxTreeAll">

<?php print($this->tree); ?>


<script type="text/javascript" src="/library/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.checkboxTreeTramite').click(function(){
            $.post('/index/alterTree/',{
                id:$(this).val(),
                status:$(this).is(':checked')
            },function(response){
                alert('response::'+response);
            });
        });
        $('.checkboxTreeAll').click(function(){
            
            var selected = [];
            
            $('.checkboxTreeTramite').attr('checked', $(this).is(':checked'));
            
            $.each($('.checkboxTreeTramite'), function(a,b){
                selected.push(b.value);
            });
           
            $.post('/index/alterTreeMultiples/',{
                ids:selected,
                status:$(this).is(':checked')
            },function(response){
                alert('response::'+response);
            });
            
        });
    });
</script>