<div class="row-fluid">
    <!--COLUNA I-->
    <div class="span4">
        <div class="row-fluid">
            <!--FOTO JOGADOR -->
            <div class="span12">
                <div class="black-box">
                    <div class="tab-header"><?php print($this->jogador->nm_abreviado); ?></div>
                    <div class="padded">
                        <img class="img-rounded" src="img/jogadores/fotos/<?php print($this->jogador->id_jogador); ?>.png">
                    </div>
                </div>
            </div>
            <!--INFORMACOES JOGADOR-->
            <div class="span12">
                <div class="black-box">
                    <div class="tab-header">Informações</div>
                    <div class="padded">
                        <p>N. Completo: <br><strong><?php print($this->jogador->nm_completo); ?></strong></strong></p>
                        <hr>
                        <p>Nascimento: <strong><?php print($this->jogador->dt_nascimento); ?></strong></strong></p>
                        <hr>
                        <p>Nacionalidade: <strong><?php print($this->jogador->nm_pais); ?></strong></strong></p>
                        <hr>
                        <p>Altura: <strong><?php print($this->jogador->nu_altura); ?> cm</strong></strong></p>
                        <p>Peso: <strong><?php print($this->jogador->nu_peso); ?> kg</strong></strong></p>
                        <hr>
                        <p>Clube: <br><strong><?php print($this->jogador->nm_clube); ?></strong></p>
                        <hr>
                        <p>Seleção: <br><strong><?php print($this->jogador->nm_selecao); ?></strong></p>
                        <hr>
                        <p>Ataque: <br><strong><?php print($this->jogador->tx_ataque); ?></strong></p>
                        <hr>
                        <p>Defesa: <br><strong><?php print($this->jogador->tx_defesa); ?></strong></p>
                        <hr>
                        <p>Pe preferido: <br><strong><?php print($this->jogador->tx_pe_preferido); ?></strong></p>
                        <hr>
                        <p>Posição I: <strong><?php print($this->jogador->cd_po_preferida_1); ?></strong></p>
                        <p>Posição II: <strong><?php print($this->jogador->cd_po_preferida_2); ?></strong></p>
                        <p>Posição III: <strong><?php print($this->jogador->cd_po_preferida_3); ?></strong></p>
                    </div>
                </div>
            </div>
            <!--CLUBE JOGADOR-->
            <div class="span12">
                <div class="black-box">
                    <div class="tab-header"><?php print($this->jogador->nm_clube); ?></div>
                    <div class="padded">
                        <img class="img-rounded" src="img/clubes/logos/<?php print($this->jogador->id_clube); ?>.png">
                    </div>
                </div>
            </div>
            <!--EQUIPE JOGADOR-->
            <div class="span12">
                <div class="black-box">
                    <div class="tab-header"><?php print($this->jogador->nm_clube); ?></div>
                    <div class="padded">
                        <img class="img-rounded" src="img/clubes/logos/<?php print($this->jogador->id_clube); ?>.png">
                    </div>
                </div>
            </div>
            <!--SELECAO JOGADOR-->
            <div class="span12">
                <div class="black-box">
                    <div class="tab-header"><?php print($this->jogador->nm_selecao); ?></div>
                    <div class="padded">
                        <img class="img-rounded" src="img/selecoes/logos/<?php print($this->jogador->id_selecao); ?>.png">
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--COLUNA II-->
    <div class="span8">
        <div class="row-fluid">
            <!--SCORES DO JOGADOR-->
            <div class="span12">
                <div class="black-box">
                    <div class="tab-header">Scores</div>
                    <div class="padded">
                        <?php
                        foreach ($this->attrs as $key => $field) :
                            $attr = key($field);
                            $value = "nm_{$attr}";
                            print '<span class="">' . $field[$attr] . ' (' . $this->jogador->{$attr} . ')</span>';

                            $color = '';

                            if ($this->jogador->{$attr} <= 25) {
                                $color = 'progress-danger';
                            }

                            if ($this->jogador->{$attr} > 25 && $this->jogador->{$attr} <= 50) {
                                $color = 'progress-warning';
                            }

                            if ($this->jogador->{$attr} > 50 && $this->jogador->{$attr} <= 75) {
                                $color = 'progress-info';
                            }

                            if ($this->jogador->{$attr} > 75) {
                                $color = 'progress-success';
                            }
                            ?>

                            <div class="input">
                                <?php if ($color): ?>
                                    <div class="progress <?php print($color); ?>" style="margin-bottom: 9px;">
                                        <div title="<?php print($this->jogador->{$attr}); ?>" class="bar" style="width: <?php print($this->jogador->{$attr}); ?>%"></div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>