<?php
$js1 = array(
    array("library/datatables/plugins/jquery.dataTables.columnFilter.js", true),
    array("library/datatables/plugins/jquery.dataTables.filteringDelay.js", true),
);

br\com\cf\library\core\cache\Cache::factory()->js($js1)->output()->clean();
?>

<style type="text/css">
    .dataTables_filter{
        display: none;
    }
    #btnDetailJogadorUser,#btnDetailJogadorAdmin{
        cursor: pointer;
    }
</style>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Jogadores</a></li>
                        <li><a href="#"><i class="icon-home"></i> Listar Todos</a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i title="Pesquisa Avançada" id="bthSearchJogadorAdmin" class="icon-search"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div id="rowSearchJogadorAdmin" class="row-fluid hidden">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Pesquisa Avançada
                        <span class="pull-left">
                            <span class="options">
                                <a href="#"><i class="icon-search"></i></a>
                            </span>
                        </span>
                    </div>
                    <?php
                    $left = $right = '';
                    foreach ($this->columns as $key => $attr) {

                        $visible = '';

                        if (current($attr) == 'Clube') {
                            $visible = 'hide';
                        }

                        if (current($attr) == 'Seleção') {
                            $visible = 'hide';
                        }

                        if ($key % 2 == 0) {
                            $left .= '<div class="input ' . $visible . '">' . current($attr) . '<span id="filterListJogadorAdmin-' . current($attr) . '"></span></div>';
                        } else {
                            $right .= '<div class="input ' . $visible . '">' . current($attr) . '<span id="filterListJogadorAdmin-' . current($attr) . '"></span></div>';
                        }

                        $visible = '';
                    }
                    ?>
                    <form class="fill-up">
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="padded">
                                    <?php print ($left); ?>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="padded">
                                    <?php print ($right); ?>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="padded">
                                    Clube <input id="fieldFilterGridClubeJogadorAdmin-target" type="text">
                                    <img class="mini-img-in-grid" id="fieldFilterGridClubeJogadorAdmin-logo">
                                    Seleção <input id="fieldFilterGridSelecaoJogadorAdmin-target" type="text">
                                    <img class="mini-img-in-grid" id="fieldFilterGridSelecaoJogadorAdmin-logo">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="button blue" type="submit">Pesquisar</button>
                            <button class="button" type="reset">Limpar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    Jogadores
                    <span class="pull-left">
                        <span class="options">
                            <a href="#"><i class="icon-user"></i></a>
                        </span>
                    </span>
                </div>
                <div>
                    <table id="gridJogadorAdmin" class="table table-striped table-condensed">
                        <thead>
                            <?php foreach ($this->columns as $key => $attr): ?>
                            <th>
                            <div><?php print current($attr); ?></div>
                            </th>
                        <?php endforeach; ?>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
        <?php print br\com\cf\library\core\view\View::partials('footer'); ?>
    </div>
</section>

<script type="text/javascript">

    $(document).ready(function() {

        $("#btnDetailJogadorAdmin").die('click').live('click', function() {
            Util.showModal('Informações Jogador', 'Editar', '/jogador/formEdit/id_jogador/' + $(this).attr('id_jogador'));
        });

        $("#btnDetailJogadorUser").die('click').live('click', function() {
            Util.showModal('Informações Jogador', 'Editar', '/jogador/detail/id_jogador/' + $(this).attr('id_jogador'));
        });

        $('#bthSearchJogadorAdmin').click(function() {
            Index.admin.btnSearchJogadorAdminHiddenToggle = !Index.admin.btnSearchJogadorAdminHiddenToggle;
            if (Index.admin.btnSearchJogadorAdminHiddenToggle) {
                $('#rowSearchJogadorAdmin').addClass('hidden');
            } else {
                $('#rowSearchJogadorAdmin').removeClass('hidden');
            }
        });

        $("#fieldFilterGridClubeJogadorAdmin-target").keyup(function() {
            if ($(this).val() === '') {
                $("#filterListJogadorAdmin-Clube .text_filter").val('').keyup();
                $("#fieldFilterGridClubeJogadorAdmin-logo").attr("src", "");
            }
        });

        $("#fieldFilterGridSelecaoJogadorAdmin-target").keyup(function() {
            if ($(this).val() === '') {
                $("#filterListJogadorAdmin-Seleção .text_filter").val('').keyup();
                $("#fieldFilterGridSelecaoJogadorAdmin-logo").attr("src", "");
            }
        });

        Index.admin.autocompleteFilterGridClubeJogadorAdmin = $("#fieldFilterGridClubeJogadorAdmin-target").autocomplete({
            minLength: 0,
            source: "/clube/autocomplete/ajax/true",
            focus: function(event, ui) {
                return false;
            },
            select: function(event, ui) {
                $("#fieldFilterGridClubeJogadorAdmin-target").val(ui.item.label);
                $("#filterListJogadorAdmin-Clube .text_filter").val(ui.item.id).keyup();
                $("#fieldFilterGridClubeJogadorAdmin-logo").attr("src", "/img/clubes/logos/" + ui.item.id + ".png");
                return false;
            }
        });

        Index.admin.autocompleteFilterGridSelecaoJogadorAdmin = $("#fieldFilterGridSelecaoJogadorAdmin-target").autocomplete({
            minLength: 0,
            source: "/selecao/autocomplete/ajax/true",
            focus: function(event, ui) {
                return false;
            },
            select: function(event, ui) {
                $("#fieldFilterGridSelecaoJogadorAdmin-target").val(ui.item.label);
                $("#filterListJogadorAdmin-Seleção .text_filter").val(ui.item.id).keyup();
                $("#fieldFilterGridSelecaoJogadorAdmin-logo").attr("src", "/img/selecoes/logos/" + ui.item.id + ".png");
                return false;
            }
        });

        Index.admin.gridJogadorAdmin = $('#gridJogadorAdmin').dataTable({
            "bFilter": true,
            "bProcessing": true,
            "bServerSide": true,
            "sPaginationType": "full_numbers",
            "bJQueryUI": false,
            "sAjaxSource": "/jogador/loadGridSearch/ajax/true/",
            "aoColumnDefs": [
                {"sName": "equals", "aTargets": [0]},
                {"sName": "like", "aTargets": [1]},
                {"sName": "like", "aTargets": [2]},
                {"sName": "equals", "aTargets": [3]},
                {"sName": "equals", "aTargets": [4]},
                {"sName": "like", "aTargets": [5]},
                {"sName": "like", "aTargets": [6]},
                {"sName": "equals", "aTargets": [7]},
                {"sName": "equals", "aTargets": [8]},
                {"sName": "equals", "aTargets": [9]}
            ],
            "oLanguage": {
                "oPaginate": {
                    "sFirst": "Primeira",
                    "sPrevious": "Anterior",
                    "sNext": "Próxima",
                    "sLast": "Última"
                },
                "sLengthMenu": "_MENU_",
                "sZeroRecords": "Nenhum jogador encontrado",
                "sInfo": "Visualizando _START_ até _END_ de _TOTAL_ jogadores",
                "sInfoEmpty": "Visualizando 0 até 0 de 0 jogadores",
                "sInfoFiltered": "(filtrado de _MAX_ jogadores)"
            },
            "fnRowCallback": function(nRow, aData, iDisplayIndex) {
                $('td:eq(0)', nRow).html('<img id="btnDetailJogadorAdmin" id_jogador="' + aData[0] + '" class="mini-img-in-grid" src="/img/jogadores/fotos/' + aData[0] + '.png">');
                $('td:eq(3)', nRow).html(aData[3] + ' cm');
                $('td:eq(4)', nRow).html(aData[4] + ' kg');
                $('td:eq(8)', nRow).html('<img class="mini-img-in-grid" src="/img/clubes/logos/' + aData[8] + '.png">');
                $('td:eq(9)', nRow).html('<img class="mini-img-in-grid" src="/img/selecoes/logos/' + aData[9] + '.png">');
            }
        }).columnFilter({
            sPlaceHolder: "head:before",
            aoColumns: [
<?php foreach ($this->columns as $key => $attr): ?>
                    {sSelector: "#filterListJogadorAdmin-<?php print current($attr); ?>"},
<?php endforeach; ?>
            ]}
        ).fnSetFilteringDelay(3);
    });
</script>