<script type="text/javascript" src="library/datatables/plugins/jquery.dataTables.columnFilter.js"></script>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Listar Todas Seleções</a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i class="icon-search"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row-fluid">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Pesquisar
                        <span class="pull-right">
                            <span class="options">
                                <a href="#"><i class="icon-cog"></i></a>
                            </span>
                        </span>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="padded">
                                <?php foreach ($this->columns as $key => $attr): ?>
                                    <div class="input">
                                        <span id="filterListJogadorAdmin-<?php print current($attr); ?>"></span>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="button blue">Salvar</button>
                            <button type="reset" class="button">Cancelar</button>
                            <div class="pull-right">
                                <div class="input">
                                    <input id="fg_perfil" class="normal-check" type="checkbox" name="fg_perfil">
                                    <label for="fg_perfil">Este usuário é Administrador?</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="box" style="position:relative;">
                <div class="tab-header">
                    Jogadores
                </div>
                <div  class="dataTables_wrapper" role="grid">
                    <table id="tabela" class="table table-striped data-table dataTable">
                        <thead>
                            <?php foreach ($this->columns as $key => $attr): ?>
                            <th>
                            <div><?php print current($attr); ?></div>
                            </th>
                        <?php endforeach; ?>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">

    $('#tabela').dataTable({
        "bProcessing": false,
        "bServerSide": true,
        "sPaginationType": "full_numbers",
        "bJQueryUI": false,
        "sAjaxSource": "/jogador/loadGridSearch/ajax/true/",
        "oLanguage": {
            "sLengthMenu": "mostrar _MENU_",
            "sZeroRecords": "nenhum jogador encontrado",
            "sInfo": "mostrando _START_ até _END_ de _TOTAL_ jogadores",
            "sInfoEmpty": "mostrando 0 até 0 de 0 jogadores",
            "sInfoFiltered": "(filtrado de _MAX_ jogadores)"
        },
        "fnRowCallback": function(nRow, aData, iDisplayIndex) {
            $('td:eq(0)', nRow).html('<img class="avatar" src="/img/jogadores/fotos/' + aData[0] + '.png">');
            $('td:eq(3)', nRow).html(aData[3] + ' cm');
            $('td:eq(4)', nRow).html(aData[4] + ' kg');
        }
    }).columnFilter({
        sPlaceHolder: "head:after",
        aoColumns: [
<?php foreach ($this->columns as $key => $attr): ?>
                {sSelector: "#filterListJogadorAdmin-<?php print current($attr); ?>"},
<?php endforeach; ?>
        ]}
    );

</script>