<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i> Pesquisar Seleções</a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i class="icon-search"></i></a>
                </div>
            </div>

            <div class="row-fluid search-bar-nav">
                <div class="span12">
                    <form>
                        <input class="search" placeholder="Search..." type="text">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Forms
                        <span class="pull-right">
                            <span class="options">
                                <a href="#"><i class="icon-cog"></i></a>
                            </span>
                        </span>
                    </div>
                    <form class="fill-up">
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="padded">
                                    <div class="input">
                                        <input placeholder="Email" type="text">
                                    </div>
                                    <div class="input">
                                        <input placeholder="Address" type="text">
                                    </div>
                                    <div class="input">
                                        <input placeholder="Username" class="error" type="text">
                                        <span data-original-title="" class="input-error" data-title="please write a valid username">
                                            <i class="icon-warning-sign"></i>
                                        </span>
                                    </div>

                                    <div class="input">
                                        <input placeholder="Password" class="error" type="password">
                                        <span data-original-title="" class="input-error" data-title="please write a valid password">
                                            <i class="icon-warning-sign"></i>
                                        </span>
                                    </div>

                                    <div class="note pull-right">Please use a secure password</div>

                                    <div class="input">
                                        <select style="display: none;" name="city" id="city" placeholder="City" class="fill-up chzn-select chzn-done">
                                            <option>Seattle</option>
                                            <option>Chicago</option>
                                            <option>New York</option>
                                        </select><div style="width: 739px;" class="chzn-container chzn-container-single" id="city_chzn"><a href="javascript:void(0)" class="chzn-single"><span>Seattle</span><div><b></b></div></a><div class="chzn-drop" style="left: -9000px; width: 737px; top: 30px;"><div class="chzn-search"><input style="width: 702px;" autocomplete="off" type="text"></div><ul class="chzn-results"><li id="city_chzn_o_0" class="active-result result-selected" style="">Seattle</li><li id="city_chzn_o_1" class="active-result" style="">Chicago</li><li id="city_chzn_o_2" class="active-result" style="">New York</li></ul></div></div>
                                    </div>


                                    <div class="input" style="padding-top: 20px;">
                                        <select style="margin-top: 20px; display: none;" multiple="multiple" name="city2" id="city2" placeholder="City" class="fill-up chzn-select chzn-done">
                                            <option>Seattle</option>
                                            <option>Chicago</option>
                                            <option>New York</option>
                                        </select><div style="width: 739px;" class="chzn-container chzn-container-multi" id="city2_chzn"><ul class="chzn-choices"><li class="search-field"><input value="Select Some Options" class="default" autocomplete="off" style="width: 149px;" type="text"></li></ul><div class="chzn-drop" style="left: -9000px; width: 737px; top: 29px;"><ul class="chzn-results"><li id="city2_chzn_o_0" class="active-result" style="">Seattle</li><li id="city2_chzn_o_1" class="active-result" style="">Chicago</li><li id="city2_chzn_o_2" class="active-result" style="">New York</li></ul></div></div>
                                    </div>

                                    <div class="input">
                                        <textarea style="display: none;" class="tagme" placeholder="This is a textarea"></textarea><div class="tagify-container"><input placeholder="add tags" type="text"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="span6">

                                <div class="padded" style="padding-bottom: 0">
                                    <div class="input">
                                        <textarea placeholder="This is a textarea" rows="6"></textarea>
                                    </div>

                                    <div class="row-fluid">

                                        <div class="span6">
                                            <div class="input">
                                                <input id="ch1" class="normal-check" type="checkbox">
                                                <label for="ch1">The number one option</label>
                                            </div>
                                            <div class="input">
                                                <input id="ch2" class="normal-check" type="checkbox">
                                                <label for="ch2">The number two option</label>
                                            </div>
                                        </div>
                                        <div class="span6">
                                            <div class="input">
                                                <input id="ch3" class="normal-check" type="checkbox">
                                                <label for="ch3">The number three option</label>
                                            </div>
                                            <div class="input">
                                                <input id="ch4" class="normal-check" type="checkbox">
                                                <label for="ch4">The number four option</label>
                                            </div>
                                        </div>
                                    </div>

                                    <input id="datetimepicker" class="fill-up hasDatepicker" value="jQuery date time picker" type="text">

                                    <div class="row-fluid">

                                        <div class="span6">
                                            <div class="input">
                                                <input name="radios[]" id="rd1" class="normal-radio" type="radio">
                                                <label for="rd1">The number one option</label>
                                            </div>

                                            <div class="input">
                                                <input name="radios[]" id="rd2" class="normal-radio" type="radio">
                                                <label for="rd2">The number two option</label>
                                            </div>
                                        </div>
                                        <div class="span6">
                                            <div class="input">
                                                <input name="radios[]" id="rd3" class="normal-radio" type="radio">
                                                <label for="rd3">The number two option</label>
                                            </div>
                                            <div class="input">
                                                <input name="radios[]" id="rd4" class="normal-radio" type="radio">
                                                <label for="rd4">The number four option</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row-fluid">
                                        <div class="span12">

                                            <div class="note large">
                                                <i class="icon-warning-sign"></i> Warning: You have to complete all fields
                                            </div>
                                            <div class="note large">
                                                <i class="icon-pencil"></i> Note: The checkboxes and radios are turned on-off entirely out of css. no javascript involved!
                                            </div>

                                            <p>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non felis non orci congue mollis. Sed euismod magna sed nunc dignissim tincidunt. Maecenas faucibus varius elit.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="button blue">Save changes</button>
                            <button type="button" class="button">Cancel</button>
                            <div class="pull-right">
                                <span class="checky-label-left">
                                    Sign me up for tha' newsletter!
                                </span>
                                <input id="nM2aX" class="checky" type="checkbox">
                                <label for="nM2aX" class="checky"><span></span></label>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <div class="row-fluid">
            <div class="span6">

                <div class="note">Prepended transparent input</div>
                <div class="prepend-transparent">
                    <span class="add-on button">@</span><input class="input-transparent" id="prependedInput" size="16" placeholder="Username" type="text">
                </div>


                <div class="note">Appended transparent input</div>
                <div class="append-transparent">
                    <input class="input-transparent" id="appendedInput" size="16" type="text"><span class="add-on button">.00</span>
                </div>

                <div class="note">Appended transparent input with button</div>
                <div class="append-transparent">
                    <input class="input-transparent" id="appendedInput2" size="16" type="text"><button class="add-on button">GO</button>
                </div>

            </div>
            <div class="span6">
                <div class="note">Input with taking the whole space</div>
                <div><input class="input-transparent fill-up" value="some nice text" type="text"></div>

                <div class="note">Input with placeholder</div>
                <input class="input-transparent" placeholder="some nice placeholder" type="text">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="footer">
                    <div>2012 © Plastique Admin Theme</div>
                    <div>Carefully crafted by <a href="https://wrapbootstrap.com/user/andrei4002">andrei4002</a></div>
                </div>
            </div>
        </div>
    </div>
</section>