<script type="text/javascript" src="library/validate/jquery.validate-1.11.1.js"></script>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-user"></i> Master Liga </a></li>
                        <li><a href="#"><i class="icon-user"></i> Encerramento </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Encerramento
                        <span class="pull-right">
                            <span class="options">
                                <a href="#"><i class="icon-cog"></i></a>
                            </span>
                        </span>
                    </div>
                    <form id="formCloseMasterLiga" class="fill-up" action="/masterLiga/close/ajax/true" method="post">
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="padded">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="button blue">Encerrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php print br\com\cf\library\core\view\View::partials('footer'); ?>
    </div>
</section>

<script type="text/javascript">


    !(function($) {

        $(document).ready(function() {

            var formNew = $('#formCloseMasterLiga');
            var actionNew = formNew.attr('action');

            $("#formCloseMasterLiga").validate({
                errorClass: "help-inline",
                submitHandler: function() {
                    if (confirm('Você tem certeza que deseja encerrar a Master Liga ativa agora?')) {
                        $.post(actionNew, formNew.serialize(), function(response) {
                            if (response.status === 'success') {
                                formNew.each(function() {
                                    Util.reloadContainer('/masterLiga/formCreate');
                                });
                            }
                            Util.showMessageBox(response);
                        }, 'json');
                    }
                }
            });

        });

    })(jQuery);

</script>