<script type="text/javascript" src="library/validate/jquery.validate-1.11.1.js"></script>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-user"></i> Master Liga </a></li>
                        <li><a href="#"><i class="icon-user"></i> Nova </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <!--<div class="span6">-->

            <div class="box">
                <div class="tab-header">
                    Criar Nova Master Liga
                    <span class="pull-right">
                        <span class="options">
                            <a href="#"><i class="icon-trophy"></i></a>
                        </span>
                    </span>
                </div>
                <form id="formCreateMasterLiga" class="fill-up" action="/masterLiga/create/ajax/true" method="post">
                    <div class="row-fluid">
                        <div class="span4">
                            <div class="padded">
                                <div class="note pull-left">Data de Inicio</div>
                                <div class="input">
                                    <input class="required date" title="informe a data de inicio da Master Liga" placeholder="" type="date" id="dtInicioFormCreateMasterLigaFake" readonly>
                                    <input class="required date" title="informe a data de inicio da Master Liga" placeholder="" type="hidden" name="dt_inicial" id="dtInicioFormCreateMasterLiga">
                                </div>
                            </div>
                        </div>
                        <div class="span4">
                            <div class="padded">
                                <div class="note pull-left">Nome da Master Liga!</div>
                                <div class="input">
                                    <input class="required" title="informe um nome para a nova Master Liga!" placeholder="Ex. Liga de Ferias" type="text" name="nm_campeonato">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="button blue">Salvar</button>
                        <div class="pull-right">
                            <div class="input">
                                <input class="checkbox" type="checkbox" id="btnSelecionarTodosUsuariosFormCreateMasterLiga">
                                <label>Marcar todos usuarios?</label>
                            </div>
                        </div>
                    </div>


                    <?php
                    $colors = array(
                        'A' => 'blue',
                        'B' => 'green',
                        'C' => 'red',
                        'D' => 'yellow',
                        'E' => 'blue',
                        'F' => 'black',
                        'G' => 'red',
                        'H' => 'blue',
                        'I' => 'green',
                        'J' => 'red',
                        'K' => 'yellow',
                        'L' => 'blue',
                        'M' => 'black',
                        'N' => 'red',
                        'O' => 'red',
                        'P' => 'red',
                    );

                    //@todo implementar a logica para agrupar corretamente...

                    $open = true;
                    $close = false;

                    foreach ($this->series as $serie => $usuarios):
                        ?>

                        <?php if ($open % 4 == 0): $close++; ?>
                            <!--<div class="row-fluid">-->
                        <?php else: $close++; ?>
                        <?php endif; ?>

                        <div class="span8">
                            <div class="nav-menu box">
                                <ul class="nav nav-list">
                                    <li class="active">
                                        <a href="#">
                                            <input type="checkbox" class="select-all-user-series" value="<?php print($serie); ?>">
                                            <span class="pull-right badge <?php print($colors[$serie]); ?>"><?php print($serie); ?></span>
                                        </a>
                                    </li>
                                    <?php foreach ($usuarios as $usuario): ?>
                                        <li>
                                            <a class="" href="#">
                                                <input type="checkbox" serie="<?php print($serie); ?>" class="select-user-series select-user-series-<?php print($serie); ?>" name="id_usuario[<?php print("{$serie}:{$usuario->id_usuario}"); ?>]">
                                                <img class="mini-img-in-grid avatar" src="https://avatar-ssl.xboxlive.com/avatar/<?php print($usuario->lg_live); ?>/avatarpic-l.png" />
                                                <img class="mini-img-in-grid avatar" src="img/escudos/<?php print($usuario->id_usuario); ?>.png" />
                                                <span class=""><strong><?php print($usuario->nm_usuario); ?></strong> - <?php print($usuario->nm_equipe); ?></span>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>

                        <?php
                        if ($close == 4): $close = 0;
                            $open = 4;
                            ?>
                            <!--</div>-->
                        <?php endif; ?>
                        <?php
                        $open++;
                    endforeach;
                    ?>

            </div>
            <!--</div>-->
            </form>
        </div>
        <?php print br\com\cf\library\core\view\View::partials('footer'); ?>
    </div>
</section>

<script type="text/javascript">


    !(function($) {

        $(document).ready(function() {

            var formNew = $('#formCreateMasterLiga');
            var actionNew = formNew.attr('action');

            $("#formCreateMasterLiga").validate({
                errorClass: "error",
                submitHandler: function() {

                    //validar quantidade de equipes por serie...

                    var t = {};
                    var m = '';

                    $('.select-user-series').each(function() {
                        eval('t.' + $(this).attr('serie') + '=0');
                    });

                    $('.select-user-series').each(function() {
                        if (this.checked === true) {
                            eval('t.' + $(this).attr('serie') + '++');
                        }
                    });

                    $.each(t, function(i, d) {
                        if (d < 2) {
                            m += ' ' + i + ' ';
                        }
                    });

                    if (m !== '') {
                        alert('A(s) serie(s) (' + m + ') devem conter pelo menos duas equipes cada!');
                        return false;
                    }

                    if (confirm('Você tem certeza que deseja criar uma nova Master Liga agora?')) {
                        $.post(actionNew, formNew.serialize(), function(response) {
                            if (response.status === 'success') {
                                formNew.each(function() {
                                    Util.reloadContainer('/masterLiga/formClose');
                                });
                            }
                            Util.showMessageBox(response);
                        }, 'json');
                    }
                }
            });

            $('.select-all-user-series').change(function() {
                $('.select-user-series-' + $(this).val()).attr('checked', this.checked);
            });

            $('#btnSelecionarTodosUsuariosFormCreateMasterLiga').change(function() {

                var checked = this.checked;

                $('.select-all-user-series').each(function() {
                    $(this).attr('checked', checked);
                }).change();

            });

            $('#dtInicioFormCreateMasterLigaFake').datepicker({
                minDate: 0,
                dateFormat: 'dd/mm/yy',
                altField: "#dtInicioFormCreateMasterLiga",
                altFormat: "yy-mm-dd"
            });

        });

    })(jQuery);

</script>