<script type="text/javascript" src="library/validate/jquery.validate-1.11.1.js"></script>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-trophy"></i> Master Liga </a></li>
                        <li><a href="#"><i class="icon-cog"></i> Configurações </a></li>
                    </ul>
                    <a class="search-button-trigger" href="#"><i class="icon-search"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Configurações da temporada
                        <span class="pull-right">
                            <span class="options">
                                <a href="#"><i class="icon-cog"></i></a>
                            </span>
                        </span>
                    </div>
                    <form id="formEditConfiguracao" class="fill-up" action="/masterLiga/configuration/ajax/true" method="post">
                        <div class="row-fluid">

                            <div class="span3">
                                <div class="padded">
                                    <?php foreach ($this->columns[0] as $key => $label): ?>
                                        <div class="note pull-left"><?php print ($label); ?></div>
                                        <div class="input input-mini">
                                            <select class="required input-small" name="<?php print ($key); ?>" value="<?php print ($this->configuracao->{$key}); ?>">
                                                <option value="1" <?php print ($this->configuracao->{$key} == 1) ? 'selected="selected"' : ''; ?>>sim</option>
                                                <option value="0" <?php print ($this->configuracao->{$key} == 0) ? 'selected="selected"' : ''; ?>>Não</option>
                                            </select>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="padded">
                                    <?php foreach ($this->columns[1] as $key => $label): ?>
                                        <div class="note pull-left"><?php print ($label); ?></div>
                                        <div class="input input-mini">
                                            <input class="required number"  type="text" name="<?php print ($key); ?>" value="<?php print ($this->configuracao->{$key}); ?>">
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="padded">
                                    <?php foreach ($this->columns[2] as $key => $label): ?>
                                        <div class="note pull-left"><?php print ($label); ?></div>
                                        <div class="input input-mini">
                                            <input class="required number"  type="text" name="<?php print ($key); ?>" value="<?php print ($this->configuracao->{$key}); ?>">
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div class="span3">
                                <div class="padded">
                                    <div class="note pull-left">Início do Draft</div>
                                    <div class="input input-medium">
                                        <input class="required date"  type="date" id="dtInicioDraftFormConfigurationFake" value="<?php print (\br\com\cf\library\core\utils\Utils::formatDate($this->configuracao->dt_inicio_draft, 'd/m/Y')); ?>" readonly>
                                        <input class="required date"  type="hidden" id="dtInicioDraftFormConfiguration" name="dt_inicio_draft" value="<?php print ($this->configuracao->dt_inicio_draft); ?>">
                                        <input class="required date"  type="hidden" name="id_configuracao" value="<?php print ($this->configuracao->id_configuracao); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="button blue">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php print br\com\cf\library\core\view\View::partials('footer'); ?>
    </div>
</section>

<script type="text/javascript">


    !(function($) {

        $(document).ready(function() {

            var formNew = $('#formEditConfiguracao');
            var actionNew = formNew.attr('action');

            $("#formEditConfiguracao").validate({
                errorClass: 'error',
                validClass: 'success',
                submitHandler: function() {
                    if (confirm('Você tem certeza que deseja alterar as configurações da Master Liga atual?')) {
                        $.post(actionNew, formNew.serialize(), function(response) {
                            Util.showMessageBox(response);
                        }, 'json');
                    }
                }
            });

            $('#dtInicioDraftFormConfigurationFake').datepicker({
                minDate: 0,
                dateFormat: 'dd/mm/yy',
                altField: "#dtInicioDraftFormConfiguration",
                altFormat: "yy-mm-dd"
            });

        });

    })(jQuery);

</script>