<script type="text/javascript" src="library/validate/jquery.validate-1.11.1.js"></script>

<section id="main">
    <div class="top-nav">
        <div class="container-fluid">
            <div class="row-fluid search-button-bar-container">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-user"></i> Master Liga </a></li>
                        <li><a href="#"><i class="icon-user"></i> Nova </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">

                <div class="box">
                    <div class="tab-header">
                        Criar Nova Master Liga
                        <span class="pull-right">
                            <span class="options">
                                <a href="#"><i class="icon-trophy"></i></a>
                            </span>
                        </span>
                    </div>
                    <form id="formCreateMasterLiga" class="fill-up" action="/masterLiga/create/ajax/true" method="post">
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="padded">
                                    <div class="note pull-left">defina uma senha segura!</div>
                                    <div class="input">
                                        <input class="required" title="informe o nome completo!" placeholder="Nome Completo" type="text" name="nm_usuario">
                                    </div>
                                    <div class="note pull-left">defina uma senha segura!</div>
                                    <div class="input">
                                        <input class="required" title="informe um email válido!" placeholder="Email" type="email" name="tx_email">
                                    </div>
                                    <div class="note pull-left">defina uma senha segura!</div>
                                    <div class="input">
                                        <input class="required" title="informe um nick válido da live!" placeholder="Nick Live" type="text" name="lg_live">
                                    </div>
                                    <div class="note pull-left">defina uma senha segura!</div>
                                    <div class="input">
                                        <input class="required" title="informe um senha segura!" placeholder="Senha" class="error" type="password" name="tx_senha">
                                    </div>



                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="button blue">Salvar</button>
                            <button type="reset" class="button">Cancelar</button>
                        </div>
                    </form>
                </div>

                <?php
                $colors = array(
                    'A' => 'blue',
                    'B' => 'green',
                    'C' => 'red',
                    'D' => 'yellow',
                    'E' => 'blue',
                    'F' => 'black',
                    'G' => 'red',
                    'H' => 'blue',
                    'I' => 'green',
                    'J' => 'red',
                    'K' => 'yellow',
                    'L' => 'blue',
                    'M' => 'black',
                    'N' => 'red',
                    'O' => 'red',
                    'P' => 'red',
                );

                //@todo implementar a logica para agrupar corretamente...

                $open = true;
                $close = false;

                foreach (array('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P') as $key => $value):
                    ?>

                    <?php if ($open % 4 == 0): $close++; ?>
                        <div class="row-fluid">
                        <?php else: $close++; ?>
                        <?php endif; ?>

                        <div class="span2">
                            <div class="nav-menu box">
                                <ul class="nav nav-list">
                                    <li class="active">
                                        <a href="#">
                                            <input type="checkbox">
                                            <span class="pull-right badge <?php print($colors[$value]); ?>"><?php print($value); ?></span>
                                        </a>
                                    </li>
                                    <?php foreach (array(1, 2, 3, 4, 5, 6, 7) as $key => $value): ?>
                                        <li>
                                            <a class="" href="#">
                                                <input type="checkbox">
                                                <img class="mini-img-in-grid avatar" src="https://avatar-ssl.xboxlive.com/avatar/cerberosnash/avatarpic-l.png" />
                                                <img class="mini-img-in-grid avatar" src="img/escudos/36.png" />
                                                <span class=""><strong>Michael</strong> - Matadores</span>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>

                        <?php
                        if ($close == 4): $close = 0;
                            $open = 4;
                            ?>
                        </div>
                    <?php endif; ?>
                    <?php
                    $open++;
                endforeach;
                ?>

            </div>
        </div>
        <?php print br\com\cf\library\core\view\View::partials('footer'); ?>
    </div>
</section>

<script type="text/javascript">


    !(function($) {

        $(document).ready(function() {

            var formNew = $('#formCreateMasterLiga');
            var actionNew = formNew.attr('action');

            $("#formCreateMasterLiga").validate({
                errorClass: "error",
                submitHandler: function() {
                    if (confirm('Você tem certeza que deseja criar uma nova Master Liga agora?')) {
                        $.post(actionNew, formNew.serialize(), function(response) {
                            if (response.status === 'success') {
                                formNew.each(function() {
                                    this.reset();
                                });
                            }
                            Util.showMessageBox(response);
                        }, 'json');
                    }
                }
            });

        });

    })(jQuery);

</script>